// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm_action.proto

package com.hello.suripu.api.expansions;

public final class ExpansionProtos {
  private ExpansionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AlarmActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hello.AlarmAction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 unix_time = 1;</code>
     */
    boolean hasUnixTime();
    /**
     * <code>optional uint64 unix_time = 1;</code>
     */
    long getUnixTime();

    /**
     * <code>optional string device_id = 2;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>optional string device_id = 2;</code>
     */
    String getDeviceId();
    /**
     * <code>optional string device_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>optional uint64 expected_ringtime_utc = 3;</code>
     */
    boolean hasExpectedRingtimeUtc();
    /**
     * <code>optional uint64 expected_ringtime_utc = 3;</code>
     */
    long getExpectedRingtimeUtc();

    /**
     * <code>optional uint64 expansion_id = 4;</code>
     */
    boolean hasExpansionId();
    /**
     * <code>optional uint64 expansion_id = 4;</code>
     */
    long getExpansionId();
  }
  /**
   * Protobuf type {@code hello.AlarmAction}
   */
  public static final class AlarmAction extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hello.AlarmAction)
      AlarmActionOrBuilder {
    // Use AlarmAction.newBuilder() to construct.
    private AlarmAction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AlarmAction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AlarmAction defaultInstance;
    public static AlarmAction getDefaultInstance() {
      return defaultInstance;
    }

    public AlarmAction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AlarmAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              unixTime_ = input.readUInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              deviceId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              expectedRingtimeUtc_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              expansionId_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExpansionProtos.internal_static_hello_AlarmAction_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExpansionProtos.internal_static_hello_AlarmAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AlarmAction.class, Builder.class);
    }

    public static com.google.protobuf.Parser<AlarmAction> PARSER =
        new com.google.protobuf.AbstractParser<AlarmAction>() {
      public AlarmAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlarmAction(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<AlarmAction> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UNIX_TIME_FIELD_NUMBER = 1;
    private long unixTime_;
    /**
     * <code>optional uint64 unix_time = 1;</code>
     */
    public boolean hasUnixTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 unix_time = 1;</code>
     */
    public long getUnixTime() {
      return unixTime_;
    }

    public static final int DEVICE_ID_FIELD_NUMBER = 2;
    private Object deviceId_;
    /**
     * <code>optional string device_id = 2;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string device_id = 2;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPECTED_RINGTIME_UTC_FIELD_NUMBER = 3;
    private long expectedRingtimeUtc_;
    /**
     * <code>optional uint64 expected_ringtime_utc = 3;</code>
     */
    public boolean hasExpectedRingtimeUtc() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 expected_ringtime_utc = 3;</code>
     */
    public long getExpectedRingtimeUtc() {
      return expectedRingtimeUtc_;
    }

    public static final int EXPANSION_ID_FIELD_NUMBER = 4;
    private long expansionId_;
    /**
     * <code>optional uint64 expansion_id = 4;</code>
     */
    public boolean hasExpansionId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 expansion_id = 4;</code>
     */
    public long getExpansionId() {
      return expansionId_;
    }

    private void initFields() {
      unixTime_ = 0L;
      deviceId_ = "";
      expectedRingtimeUtc_ = 0L;
      expansionId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, unixTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, expectedRingtimeUtc_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, expansionId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, unixTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, expectedRingtimeUtc_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, expansionId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static AlarmAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlarmAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlarmAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlarmAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlarmAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AlarmAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static AlarmAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static AlarmAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static AlarmAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AlarmAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(AlarmAction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hello.AlarmAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hello.AlarmAction)
        AlarmActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ExpansionProtos.internal_static_hello_AlarmAction_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ExpansionProtos.internal_static_hello_AlarmAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AlarmAction.class, Builder.class);
      }

      // Construct using com.hello.suripu.api.expansions.ExpansionProtos.AlarmAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        unixTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        expectedRingtimeUtc_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        expansionId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ExpansionProtos.internal_static_hello_AlarmAction_descriptor;
      }

      public AlarmAction getDefaultInstanceForType() {
        return AlarmAction.getDefaultInstance();
      }

      public AlarmAction build() {
        AlarmAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AlarmAction buildPartial() {
        AlarmAction result = new AlarmAction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unixTime_ = unixTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.expectedRingtimeUtc_ = expectedRingtimeUtc_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.expansionId_ = expansionId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AlarmAction) {
          return mergeFrom((AlarmAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AlarmAction other) {
        if (other == AlarmAction.getDefaultInstance()) return this;
        if (other.hasUnixTime()) {
          setUnixTime(other.getUnixTime());
        }
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000002;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasExpectedRingtimeUtc()) {
          setExpectedRingtimeUtc(other.getExpectedRingtimeUtc());
        }
        if (other.hasExpansionId()) {
          setExpansionId(other.getExpansionId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AlarmAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AlarmAction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long unixTime_ ;
      /**
       * <code>optional uint64 unix_time = 1;</code>
       */
      public boolean hasUnixTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 unix_time = 1;</code>
       */
      public long getUnixTime() {
        return unixTime_;
      }
      /**
       * <code>optional uint64 unix_time = 1;</code>
       */
      public Builder setUnixTime(long value) {
        bitField0_ |= 0x00000001;
        unixTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 unix_time = 1;</code>
       */
      public Builder clearUnixTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unixTime_ = 0L;
        onChanged();
        return this;
      }

      private Object deviceId_ = "";
      /**
       * <code>optional string device_id = 2;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string device_id = 2;</code>
       */
      public String getDeviceId() {
        Object ref = deviceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string device_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_id = 2;</code>
       */
      public Builder setDeviceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 2;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 2;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceId_ = value;
        onChanged();
        return this;
      }

      private long expectedRingtimeUtc_ ;
      /**
       * <code>optional uint64 expected_ringtime_utc = 3;</code>
       */
      public boolean hasExpectedRingtimeUtc() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 expected_ringtime_utc = 3;</code>
       */
      public long getExpectedRingtimeUtc() {
        return expectedRingtimeUtc_;
      }
      /**
       * <code>optional uint64 expected_ringtime_utc = 3;</code>
       */
      public Builder setExpectedRingtimeUtc(long value) {
        bitField0_ |= 0x00000004;
        expectedRingtimeUtc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 expected_ringtime_utc = 3;</code>
       */
      public Builder clearExpectedRingtimeUtc() {
        bitField0_ = (bitField0_ & ~0x00000004);
        expectedRingtimeUtc_ = 0L;
        onChanged();
        return this;
      }

      private long expansionId_ ;
      /**
       * <code>optional uint64 expansion_id = 4;</code>
       */
      public boolean hasExpansionId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 expansion_id = 4;</code>
       */
      public long getExpansionId() {
        return expansionId_;
      }
      /**
       * <code>optional uint64 expansion_id = 4;</code>
       */
      public Builder setExpansionId(long value) {
        bitField0_ |= 0x00000008;
        expansionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 expansion_id = 4;</code>
       */
      public Builder clearExpansionId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        expansionId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hello.AlarmAction)
    }

    static {
      defaultInstance = new AlarmAction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hello.AlarmAction)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_AlarmAction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hello_AlarmAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022alarm_action.proto\022\005hello\"h\n\013AlarmActi" +
      "on\022\021\n\tunix_time\030\001 \001(\004\022\021\n\tdevice_id\030\002 \001(\t" +
      "\022\035\n\025expected_ringtime_utc\030\003 \001(\004\022\024\n\014expan" +
      "sion_id\030\004 \001(\004B2\n\037com.hello.suripu.api.ex" +
      "pansionsB\017ExpansionProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hello_AlarmAction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hello_AlarmAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hello_AlarmAction_descriptor,
        new String[] { "UnixTime", "DeviceId", "ExpectedRingtimeUtc", "ExpansionId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
