package com.hello.suripu.core.flipper;

public class FeatureFlipper {

    public final static String AUDIO_STORAGE = "audio_storage";
    public final static String AUDIO_CAPTURE = "audio_capture";
    public final static String ALWAYS_ON_AUDIO = "always_on_audio";
    public final static String SOUND_INFO_TIMELINE = "sound_info_timeline";
    public final static String SMART_ALARM = "smart_alarm";
    public final static String OTA_RELEASE = "release";
    public final static String BYPASS_OTA_CHECKS = "bypass_ota_checks";
    public final static String FORCE_EVT_OTA_UPDATE = "pang-fire-fighting";
    public final static String DEBUG_MODE_PILL_PAIRING = "debug-mode-pill-pairing";
    public final static String MISSING_DATA_DEFAULT_VALUE = "missing_data_default_value";
    public final static String FORCE_HTTP_500 = "force_http_500";
    public final static String ALARM_IN_TIMELINE = "alarm_in_timeline";
    public final static String PUSH_NOTIFICATIONS_ENABLED = "push_notifications_enabled";
    public final static String SOUND_EVENTS_IN_TIMELINE = "sound_event_in_timeline";
    public final static String ENVIRONMENT_IN_TIMELINE_SCORE = "environment_in_timeline_score";
    public final static String FEEDBACK_IN_TIMELINE = "feedback_in_timeline";
    public final static String IN_OUT_BED_EVENTS = "in_out_bed_events";
    public final static String HMM_ALGORITHM = "hmm_algorithm";
    public final static String VOTING_ALGORITHM = "voting_algorithm";
    public final static String PARTNER_FILTER = "partner_filter";
    public final static String OFFICE_ONLY_OVERRIDE = "office_only_override";
    public final static String SMART_ALARM_LOGGING = "smart_alarm_log";
    public final static String PCH_SPECIAL_OTA = "pch_special_ota";
    public final static String PROGRESSIVE_SMART_ALARM = "progressive_smart_alarm";
    public final static String ALLOW_RESPONSE_COMMANDS = "allow_response_commands";
    public final static String ALL_SENSOR_QUERY_USE_UTC_TS = "all_sensor_query_user_utc_ts";
    public final static String NEW_INVALID_NIGHT_FILTER = "new_invalid_night_filter";
    public final static String SENSORS_DB_UNAVAILABLE = "sensors_db_unavailable";
    public final static String COMMON_DB_UNAVAILABLE = "common_db_unavailable";
    public final static String VIEW_SENSORS_UNAVAILABLE = "view_sensors_unavailable";
    public final static String VIEW_TIMELINE_UNAVAILABLE = "view_timeline_unavailable";
    public final static String VIEW_TRENDS_UNAVAILABLE = "view_trends_unavailable";
    public final static String RING_DURATION_FROM_CONFIG = "ring_duration_from_config";
    public final static String EXTRA_EVENTS = "extra_events";
    public final static String SENSE_LAST_SEEN_VIEW_DYNAMODB = "sense_last_seen_view_dynamodb";
    public final static String SENSE_LAST_SEEN_VIEW_DYNAMODB_READ = "sense_last_seen_view_dynamodb_read";
    public final static String REMOVE_MOTION_EVENTS_OUTSIDE_SLEEP = "remove_motion_events_outside_sleep";
    public final static String REMOVE_GREY_OUT_EVENTS = "remove_grey_out_events";
    public final static String STOP_PROCESS_TIMELINE_FROM_WORKER = "stop_process_timeline_from_worker";
    public final static String EXPIRE_TIMELINE_IN_PROCESSING_TIME_SPAN = "expire_timeline_in_processing_time_span";
    public final static String COMPENSATE_LIGHT_WITH_SENSE_COLOR = "compensate_light_with_sense_color";
    public final static String BAYESIAN_PARTNER_FILTER = "bayesian_partner_filter";
    public final static String REBOOT_CLOCK_OUT_OF_SYNC_DEVICES = "reboot_clock_out_of_sync_devices";
    public final static String REDUCE_BATCH_UPLOAD_INTERVAL = "reduce_batch_upload_interval";
    public final static String NEW_ROOM_CONDITION = "new_room_condition";
    public final static String TIMELINE_V2_AVAILABLE = "timeline_v2_available";
    public final static String BAYES_NET_ALGORITHM = "bayes_net_algorithm";
}
