// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: suripu-api/src/main/resources/protos/morpheus_ble.proto

package com.hello.suripu.api.ble;

public final class MorpheusBle {
  private MorpheusBle() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code hello.ErrorType}
   */
  public enum ErrorType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TIME_OUT = 0;</code>
     *
     * <pre>
     * Internal time out, no implemented yet.
     * </pre>
     */
    TIME_OUT(0, 0),
    /**
     * <code>NETWORK_ERROR = 1;</code>
     *
     * <pre>
     * Network not available or unreachable network.
     * </pre>
     */
    NETWORK_ERROR(1, 1),
    /**
     * <code>DEVICE_ALREADY_PAIRED = 2;</code>
     *
     * <pre>
     * User tries to paired a paired device to another account.
     * </pre>
     */
    DEVICE_ALREADY_PAIRED(2, 2),
    /**
     * <code>INTERNAL_DATA_ERROR = 3;</code>
     *
     * <pre>
     * Data packets corruption during BLE or SPI transfer
     * </pre>
     */
    INTERNAL_DATA_ERROR(3, 3),
    /**
     * <code>DEVICE_DATABASE_FULL = 4;</code>
     *
     * <pre>
     * No more space for device pairing.
     * </pre>
     */
    DEVICE_DATABASE_FULL(4, 4),
    /**
     * <code>DEVICE_NO_MEMORY = 5;</code>
     *
     * <pre>
     * Device run out of heap
     * </pre>
     */
    DEVICE_NO_MEMORY(5, 5),
    /**
     * <code>INTERNAL_OPERATION_FAILED = 6;</code>
     */
    INTERNAL_OPERATION_FAILED(6, 6),
    ;

    /**
     * <code>TIME_OUT = 0;</code>
     *
     * <pre>
     * Internal time out, no implemented yet.
     * </pre>
     */
    public static final int TIME_OUT_VALUE = 0;
    /**
     * <code>NETWORK_ERROR = 1;</code>
     *
     * <pre>
     * Network not available or unreachable network.
     * </pre>
     */
    public static final int NETWORK_ERROR_VALUE = 1;
    /**
     * <code>DEVICE_ALREADY_PAIRED = 2;</code>
     *
     * <pre>
     * User tries to paired a paired device to another account.
     * </pre>
     */
    public static final int DEVICE_ALREADY_PAIRED_VALUE = 2;
    /**
     * <code>INTERNAL_DATA_ERROR = 3;</code>
     *
     * <pre>
     * Data packets corruption during BLE or SPI transfer
     * </pre>
     */
    public static final int INTERNAL_DATA_ERROR_VALUE = 3;
    /**
     * <code>DEVICE_DATABASE_FULL = 4;</code>
     *
     * <pre>
     * No more space for device pairing.
     * </pre>
     */
    public static final int DEVICE_DATABASE_FULL_VALUE = 4;
    /**
     * <code>DEVICE_NO_MEMORY = 5;</code>
     *
     * <pre>
     * Device run out of heap
     * </pre>
     */
    public static final int DEVICE_NO_MEMORY_VALUE = 5;
    /**
     * <code>INTERNAL_OPERATION_FAILED = 6;</code>
     */
    public static final int INTERNAL_OPERATION_FAILED_VALUE = 6;


    public final int getNumber() { return value; }

    public static ErrorType valueOf(int value) {
      switch (value) {
        case 0: return TIME_OUT;
        case 1: return NETWORK_ERROR;
        case 2: return DEVICE_ALREADY_PAIRED;
        case 3: return INTERNAL_DATA_ERROR;
        case 4: return DEVICE_DATABASE_FULL;
        case 5: return DEVICE_NO_MEMORY;
        case 6: return INTERNAL_OPERATION_FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorType>() {
            public ErrorType findValueByNumber(int number) {
              return ErrorType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hello.suripu.api.ble.MorpheusBle.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorType[] VALUES = values();

    public static ErrorType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ErrorType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:hello.ErrorType)
  }

  public interface MorpheusCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 version = 1;
    /**
     * <code>required int32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     */
    int getVersion();

    // required .hello.MorpheusCommand.CommandType type = 2;
    /**
     * <code>required .hello.MorpheusCommand.CommandType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .hello.MorpheusCommand.CommandType type = 2;</code>
     */
    com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.CommandType getType();

    // optional string deviceId = 3;
    /**
     * <code>optional string deviceId = 3;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>optional string deviceId = 3;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>optional string deviceId = 3;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    // optional string accountId = 4;
    /**
     * <code>optional string accountId = 4;</code>
     *
     * <pre>
     * Used by MORPHEUS_COMMAND_PAIRE_PILL
     * </pre>
     */
    boolean hasAccountId();
    /**
     * <code>optional string accountId = 4;</code>
     *
     * <pre>
     * Used by MORPHEUS_COMMAND_PAIRE_PILL
     * </pre>
     */
    java.lang.String getAccountId();
    /**
     * <code>optional string accountId = 4;</code>
     *
     * <pre>
     * Used by MORPHEUS_COMMAND_PAIRE_PILL
     * </pre>
     */
    com.google.protobuf.ByteString
        getAccountIdBytes();

    // optional .hello.ErrorType error = 5;
    /**
     * <code>optional .hello.ErrorType error = 5;</code>
     *
     * <pre>
     * MORPHEUS_COMMAND_ERROR
     * </pre>
     */
    boolean hasError();
    /**
     * <code>optional .hello.ErrorType error = 5;</code>
     *
     * <pre>
     * MORPHEUS_COMMAND_ERROR
     * </pre>
     */
    com.hello.suripu.api.ble.MorpheusBle.ErrorType getError();

    // optional string wifiName = 6;
    /**
     * <code>optional string wifiName = 6;</code>
     */
    boolean hasWifiName();
    /**
     * <code>optional string wifiName = 6;</code>
     */
    java.lang.String getWifiName();
    /**
     * <code>optional string wifiName = 6;</code>
     */
    com.google.protobuf.ByteString
        getWifiNameBytes();

    // optional string wifiSSID = 7;
    /**
     * <code>optional string wifiSSID = 7;</code>
     */
    boolean hasWifiSSID();
    /**
     * <code>optional string wifiSSID = 7;</code>
     */
    java.lang.String getWifiSSID();
    /**
     * <code>optional string wifiSSID = 7;</code>
     */
    com.google.protobuf.ByteString
        getWifiSSIDBytes();

    // optional string wifiPassword = 8;
    /**
     * <code>optional string wifiPassword = 8;</code>
     */
    boolean hasWifiPassword();
    /**
     * <code>optional string wifiPassword = 8;</code>
     */
    java.lang.String getWifiPassword();
    /**
     * <code>optional string wifiPassword = 8;</code>
     */
    com.google.protobuf.ByteString
        getWifiPasswordBytes();

    // optional int32 batteryLevel = 9;
    /**
     * <code>optional int32 batteryLevel = 9;</code>
     */
    boolean hasBatteryLevel();
    /**
     * <code>optional int32 batteryLevel = 9;</code>
     */
    int getBatteryLevel();

    // optional int32 uptime = 10;
    /**
     * <code>optional int32 uptime = 10;</code>
     */
    boolean hasUptime();
    /**
     * <code>optional int32 uptime = 10;</code>
     */
    int getUptime();

    // optional int32 motionData = 11;
    /**
     * <code>optional int32 motionData = 11;</code>
     */
    boolean hasMotionData();
    /**
     * <code>optional int32 motionData = 11;</code>
     */
    int getMotionData();

    // optional bytes motionDataEntrypted = 12;
    /**
     * <code>optional bytes motionDataEntrypted = 12;</code>
     */
    boolean hasMotionDataEntrypted();
    /**
     * <code>optional bytes motionDataEntrypted = 12;</code>
     */
    com.google.protobuf.ByteString getMotionDataEntrypted();

    // optional int32 firmwareVersion = 13;
    /**
     * <code>optional int32 firmwareVersion = 13;</code>
     */
    boolean hasFirmwareVersion();
    /**
     * <code>optional int32 firmwareVersion = 13;</code>
     */
    int getFirmwareVersion();
  }
  /**
   * Protobuf type {@code hello.MorpheusCommand}
   */
  public static final class MorpheusCommand extends
      com.google.protobuf.GeneratedMessage
      implements MorpheusCommandOrBuilder {
    // Use MorpheusCommand.newBuilder() to construct.
    private MorpheusCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MorpheusCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MorpheusCommand defaultInstance;
    public static MorpheusCommand getDefaultInstance() {
      return defaultInstance;
    }

    public MorpheusCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MorpheusCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.CommandType value = com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              deviceId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              accountId_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.hello.suripu.api.ble.MorpheusBle.ErrorType value = com.hello.suripu.api.ble.MorpheusBle.ErrorType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                error_ = value;
              }
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              wifiName_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              wifiSSID_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              wifiPassword_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              batteryLevel_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              uptime_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              motionData_ = input.readInt32();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              motionDataEntrypted_ = input.readBytes();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              firmwareVersion_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hello.suripu.api.ble.MorpheusBle.internal_static_hello_MorpheusCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hello.suripu.api.ble.MorpheusBle.internal_static_hello_MorpheusCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.class, com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.Builder.class);
    }

    public static com.google.protobuf.Parser<MorpheusCommand> PARSER =
        new com.google.protobuf.AbstractParser<MorpheusCommand>() {
      public MorpheusCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MorpheusCommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MorpheusCommand> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code hello.MorpheusCommand.CommandType}
     */
    public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MORPHEUS_COMMAND_SET_TIME = 0;</code>
       */
      MORPHEUS_COMMAND_SET_TIME(0, 0),
      /**
       * <code>MORPHEUS_COMMAND_GET_TIME = 1;</code>
       */
      MORPHEUS_COMMAND_GET_TIME(1, 1),
      /**
       * <code>MORPHEUS_COMMAND_SET_WIFI_ENDPOINT = 2;</code>
       */
      MORPHEUS_COMMAND_SET_WIFI_ENDPOINT(2, 2),
      /**
       * <code>MORPHEUS_COMMAND_GET_WIFI_ENDPOINT = 3;</code>
       */
      MORPHEUS_COMMAND_GET_WIFI_ENDPOINT(3, 3),
      /**
       * <code>MORPHEUS_COMMAND_SET_ALARMS = 4;</code>
       */
      MORPHEUS_COMMAND_SET_ALARMS(4, 4),
      /**
       * <code>MORPHEUS_COMMAND_GET_ALARMS = 5;</code>
       */
      MORPHEUS_COMMAND_GET_ALARMS(5, 5),
      /**
       * <code>MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE = 6;</code>
       */
      MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE(6, 6),
      /**
       * <code>MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE = 7;</code>
       */
      MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE(7, 7),
      /**
       * <code>MORPHEUS_COMMAND_START_WIFISCAN = 8;</code>
       */
      MORPHEUS_COMMAND_START_WIFISCAN(8, 8),
      /**
       * <code>MORPHEUS_COMMAND_STOP_WIFISCAN = 9;</code>
       */
      MORPHEUS_COMMAND_STOP_WIFISCAN(9, 9),
      /**
       * <code>MORPHEUS_COMMAND_GET_DEVICE_ID = 10;</code>
       */
      MORPHEUS_COMMAND_GET_DEVICE_ID(10, 10),
      /**
       * <code>MORPHEUS_COMMAND_EREASE_PAIRED_PHONE = 11;</code>
       */
      MORPHEUS_COMMAND_EREASE_PAIRED_PHONE(11, 11),
      /**
       * <code>MORPHEUS_COMMAND_PAIR_PILL = 12;</code>
       */
      MORPHEUS_COMMAND_PAIR_PILL(12, 12),
      /**
       * <code>MORPHEUS_COMMAND_ERROR = 13;</code>
       *
       * <pre>
       * if you receive this, that means something goes wrong.
       * </pre>
       */
      MORPHEUS_COMMAND_ERROR(13, 13),
      /**
       * <code>MORPHEUS_COMMAND_PAIR_SENSE = 14;</code>
       */
      MORPHEUS_COMMAND_PAIR_SENSE(14, 14),
      /**
       * <code>MORPHEUS_COMMAND_UNPAIR_PILL = 15;</code>
       */
      MORPHEUS_COMMAND_UNPAIR_PILL(15, 15),
      /**
       * <code>MORPHEUS_COMMAND_MORPHEUS_DFU_BEGIN = 16;</code>
       */
      MORPHEUS_COMMAND_MORPHEUS_DFU_BEGIN(16, 16),
      /**
       * <code>MORPHEUS_COMMAND_PILL_DATA = 17;</code>
       */
      MORPHEUS_COMMAND_PILL_DATA(17, 17),
      /**
       * <code>MORPHEUS_COMMAND_PILL_HEARTBEAT = 18;</code>
       */
      MORPHEUS_COMMAND_PILL_HEARTBEAT(18, 18),
      /**
       * <code>MORPHEUS_COMMAND_PILL_DFU_BEGIN = 19;</code>
       */
      MORPHEUS_COMMAND_PILL_DFU_BEGIN(19, 19),
      ;

      /**
       * <code>MORPHEUS_COMMAND_SET_TIME = 0;</code>
       */
      public static final int MORPHEUS_COMMAND_SET_TIME_VALUE = 0;
      /**
       * <code>MORPHEUS_COMMAND_GET_TIME = 1;</code>
       */
      public static final int MORPHEUS_COMMAND_GET_TIME_VALUE = 1;
      /**
       * <code>MORPHEUS_COMMAND_SET_WIFI_ENDPOINT = 2;</code>
       */
      public static final int MORPHEUS_COMMAND_SET_WIFI_ENDPOINT_VALUE = 2;
      /**
       * <code>MORPHEUS_COMMAND_GET_WIFI_ENDPOINT = 3;</code>
       */
      public static final int MORPHEUS_COMMAND_GET_WIFI_ENDPOINT_VALUE = 3;
      /**
       * <code>MORPHEUS_COMMAND_SET_ALARMS = 4;</code>
       */
      public static final int MORPHEUS_COMMAND_SET_ALARMS_VALUE = 4;
      /**
       * <code>MORPHEUS_COMMAND_GET_ALARMS = 5;</code>
       */
      public static final int MORPHEUS_COMMAND_GET_ALARMS_VALUE = 5;
      /**
       * <code>MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE = 6;</code>
       */
      public static final int MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE_VALUE = 6;
      /**
       * <code>MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE = 7;</code>
       */
      public static final int MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE_VALUE = 7;
      /**
       * <code>MORPHEUS_COMMAND_START_WIFISCAN = 8;</code>
       */
      public static final int MORPHEUS_COMMAND_START_WIFISCAN_VALUE = 8;
      /**
       * <code>MORPHEUS_COMMAND_STOP_WIFISCAN = 9;</code>
       */
      public static final int MORPHEUS_COMMAND_STOP_WIFISCAN_VALUE = 9;
      /**
       * <code>MORPHEUS_COMMAND_GET_DEVICE_ID = 10;</code>
       */
      public static final int MORPHEUS_COMMAND_GET_DEVICE_ID_VALUE = 10;
      /**
       * <code>MORPHEUS_COMMAND_EREASE_PAIRED_PHONE = 11;</code>
       */
      public static final int MORPHEUS_COMMAND_EREASE_PAIRED_PHONE_VALUE = 11;
      /**
       * <code>MORPHEUS_COMMAND_PAIR_PILL = 12;</code>
       */
      public static final int MORPHEUS_COMMAND_PAIR_PILL_VALUE = 12;
      /**
       * <code>MORPHEUS_COMMAND_ERROR = 13;</code>
       *
       * <pre>
       * if you receive this, that means something goes wrong.
       * </pre>
       */
      public static final int MORPHEUS_COMMAND_ERROR_VALUE = 13;
      /**
       * <code>MORPHEUS_COMMAND_PAIR_SENSE = 14;</code>
       */
      public static final int MORPHEUS_COMMAND_PAIR_SENSE_VALUE = 14;
      /**
       * <code>MORPHEUS_COMMAND_UNPAIR_PILL = 15;</code>
       */
      public static final int MORPHEUS_COMMAND_UNPAIR_PILL_VALUE = 15;
      /**
       * <code>MORPHEUS_COMMAND_MORPHEUS_DFU_BEGIN = 16;</code>
       */
      public static final int MORPHEUS_COMMAND_MORPHEUS_DFU_BEGIN_VALUE = 16;
      /**
       * <code>MORPHEUS_COMMAND_PILL_DATA = 17;</code>
       */
      public static final int MORPHEUS_COMMAND_PILL_DATA_VALUE = 17;
      /**
       * <code>MORPHEUS_COMMAND_PILL_HEARTBEAT = 18;</code>
       */
      public static final int MORPHEUS_COMMAND_PILL_HEARTBEAT_VALUE = 18;
      /**
       * <code>MORPHEUS_COMMAND_PILL_DFU_BEGIN = 19;</code>
       */
      public static final int MORPHEUS_COMMAND_PILL_DFU_BEGIN_VALUE = 19;


      public final int getNumber() { return value; }

      public static CommandType valueOf(int value) {
        switch (value) {
          case 0: return MORPHEUS_COMMAND_SET_TIME;
          case 1: return MORPHEUS_COMMAND_GET_TIME;
          case 2: return MORPHEUS_COMMAND_SET_WIFI_ENDPOINT;
          case 3: return MORPHEUS_COMMAND_GET_WIFI_ENDPOINT;
          case 4: return MORPHEUS_COMMAND_SET_ALARMS;
          case 5: return MORPHEUS_COMMAND_GET_ALARMS;
          case 6: return MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE;
          case 7: return MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE;
          case 8: return MORPHEUS_COMMAND_START_WIFISCAN;
          case 9: return MORPHEUS_COMMAND_STOP_WIFISCAN;
          case 10: return MORPHEUS_COMMAND_GET_DEVICE_ID;
          case 11: return MORPHEUS_COMMAND_EREASE_PAIRED_PHONE;
          case 12: return MORPHEUS_COMMAND_PAIR_PILL;
          case 13: return MORPHEUS_COMMAND_ERROR;
          case 14: return MORPHEUS_COMMAND_PAIR_SENSE;
          case 15: return MORPHEUS_COMMAND_UNPAIR_PILL;
          case 16: return MORPHEUS_COMMAND_MORPHEUS_DFU_BEGIN;
          case 17: return MORPHEUS_COMMAND_PILL_DATA;
          case 18: return MORPHEUS_COMMAND_PILL_HEARTBEAT;
          case 19: return MORPHEUS_COMMAND_PILL_DFU_BEGIN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.getDescriptor().getEnumTypes().get(0);
      }

      private static final CommandType[] VALUES = values();

      public static CommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CommandType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:hello.MorpheusCommand.CommandType)
    }

    private int bitField0_;
    // required int32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    // required .hello.MorpheusCommand.CommandType type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.CommandType type_;
    /**
     * <code>required .hello.MorpheusCommand.CommandType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .hello.MorpheusCommand.CommandType type = 2;</code>
     */
    public com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.CommandType getType() {
      return type_;
    }

    // optional string deviceId = 3;
    public static final int DEVICEID_FIELD_NUMBER = 3;
    private java.lang.Object deviceId_;
    /**
     * <code>optional string deviceId = 3;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string deviceId = 3;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deviceId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string accountId = 4;
    public static final int ACCOUNTID_FIELD_NUMBER = 4;
    private java.lang.Object accountId_;
    /**
     * <code>optional string accountId = 4;</code>
     *
     * <pre>
     * Used by MORPHEUS_COMMAND_PAIRE_PILL
     * </pre>
     */
    public boolean hasAccountId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string accountId = 4;</code>
     *
     * <pre>
     * Used by MORPHEUS_COMMAND_PAIRE_PILL
     * </pre>
     */
    public java.lang.String getAccountId() {
      java.lang.Object ref = accountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accountId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string accountId = 4;</code>
     *
     * <pre>
     * Used by MORPHEUS_COMMAND_PAIRE_PILL
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .hello.ErrorType error = 5;
    public static final int ERROR_FIELD_NUMBER = 5;
    private com.hello.suripu.api.ble.MorpheusBle.ErrorType error_;
    /**
     * <code>optional .hello.ErrorType error = 5;</code>
     *
     * <pre>
     * MORPHEUS_COMMAND_ERROR
     * </pre>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .hello.ErrorType error = 5;</code>
     *
     * <pre>
     * MORPHEUS_COMMAND_ERROR
     * </pre>
     */
    public com.hello.suripu.api.ble.MorpheusBle.ErrorType getError() {
      return error_;
    }

    // optional string wifiName = 6;
    public static final int WIFINAME_FIELD_NUMBER = 6;
    private java.lang.Object wifiName_;
    /**
     * <code>optional string wifiName = 6;</code>
     */
    public boolean hasWifiName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string wifiName = 6;</code>
     */
    public java.lang.String getWifiName() {
      java.lang.Object ref = wifiName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          wifiName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string wifiName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getWifiNameBytes() {
      java.lang.Object ref = wifiName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wifiName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string wifiSSID = 7;
    public static final int WIFISSID_FIELD_NUMBER = 7;
    private java.lang.Object wifiSSID_;
    /**
     * <code>optional string wifiSSID = 7;</code>
     */
    public boolean hasWifiSSID() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string wifiSSID = 7;</code>
     */
    public java.lang.String getWifiSSID() {
      java.lang.Object ref = wifiSSID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          wifiSSID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string wifiSSID = 7;</code>
     */
    public com.google.protobuf.ByteString
        getWifiSSIDBytes() {
      java.lang.Object ref = wifiSSID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wifiSSID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string wifiPassword = 8;
    public static final int WIFIPASSWORD_FIELD_NUMBER = 8;
    private java.lang.Object wifiPassword_;
    /**
     * <code>optional string wifiPassword = 8;</code>
     */
    public boolean hasWifiPassword() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string wifiPassword = 8;</code>
     */
    public java.lang.String getWifiPassword() {
      java.lang.Object ref = wifiPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          wifiPassword_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string wifiPassword = 8;</code>
     */
    public com.google.protobuf.ByteString
        getWifiPasswordBytes() {
      java.lang.Object ref = wifiPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wifiPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 batteryLevel = 9;
    public static final int BATTERYLEVEL_FIELD_NUMBER = 9;
    private int batteryLevel_;
    /**
     * <code>optional int32 batteryLevel = 9;</code>
     */
    public boolean hasBatteryLevel() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 batteryLevel = 9;</code>
     */
    public int getBatteryLevel() {
      return batteryLevel_;
    }

    // optional int32 uptime = 10;
    public static final int UPTIME_FIELD_NUMBER = 10;
    private int uptime_;
    /**
     * <code>optional int32 uptime = 10;</code>
     */
    public boolean hasUptime() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 uptime = 10;</code>
     */
    public int getUptime() {
      return uptime_;
    }

    // optional int32 motionData = 11;
    public static final int MOTIONDATA_FIELD_NUMBER = 11;
    private int motionData_;
    /**
     * <code>optional int32 motionData = 11;</code>
     */
    public boolean hasMotionData() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 motionData = 11;</code>
     */
    public int getMotionData() {
      return motionData_;
    }

    // optional bytes motionDataEntrypted = 12;
    public static final int MOTIONDATAENTRYPTED_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString motionDataEntrypted_;
    /**
     * <code>optional bytes motionDataEntrypted = 12;</code>
     */
    public boolean hasMotionDataEntrypted() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional bytes motionDataEntrypted = 12;</code>
     */
    public com.google.protobuf.ByteString getMotionDataEntrypted() {
      return motionDataEntrypted_;
    }

    // optional int32 firmwareVersion = 13;
    public static final int FIRMWAREVERSION_FIELD_NUMBER = 13;
    private int firmwareVersion_;
    /**
     * <code>optional int32 firmwareVersion = 13;</code>
     */
    public boolean hasFirmwareVersion() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 firmwareVersion = 13;</code>
     */
    public int getFirmwareVersion() {
      return firmwareVersion_;
    }

    private void initFields() {
      version_ = 0;
      type_ = com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.CommandType.MORPHEUS_COMMAND_SET_TIME;
      deviceId_ = "";
      accountId_ = "";
      error_ = com.hello.suripu.api.ble.MorpheusBle.ErrorType.TIME_OUT;
      wifiName_ = "";
      wifiSSID_ = "";
      wifiPassword_ = "";
      batteryLevel_ = 0;
      uptime_ = 0;
      motionData_ = 0;
      motionDataEntrypted_ = com.google.protobuf.ByteString.EMPTY;
      firmwareVersion_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAccountIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, error_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getWifiNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getWifiSSIDBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getWifiPasswordBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, batteryLevel_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, uptime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, motionData_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, motionDataEntrypted_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, firmwareVersion_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAccountIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, error_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getWifiNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getWifiSSIDBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getWifiPasswordBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, batteryLevel_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, uptime_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, motionData_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, motionDataEntrypted_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, firmwareVersion_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hello.MorpheusCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hello.suripu.api.ble.MorpheusBle.MorpheusCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hello.suripu.api.ble.MorpheusBle.internal_static_hello_MorpheusCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hello.suripu.api.ble.MorpheusBle.internal_static_hello_MorpheusCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.class, com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.Builder.class);
      }

      // Construct using com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.CommandType.MORPHEUS_COMMAND_SET_TIME;
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        accountId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        error_ = com.hello.suripu.api.ble.MorpheusBle.ErrorType.TIME_OUT;
        bitField0_ = (bitField0_ & ~0x00000010);
        wifiName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        wifiSSID_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        wifiPassword_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        batteryLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        uptime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        motionData_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        motionDataEntrypted_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000800);
        firmwareVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hello.suripu.api.ble.MorpheusBle.internal_static_hello_MorpheusCommand_descriptor;
      }

      public com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand getDefaultInstanceForType() {
        return com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.getDefaultInstance();
      }

      public com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand build() {
        com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand buildPartial() {
        com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand result = new com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.accountId_ = accountId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.wifiName_ = wifiName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.wifiSSID_ = wifiSSID_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.wifiPassword_ = wifiPassword_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.batteryLevel_ = batteryLevel_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.uptime_ = uptime_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.motionData_ = motionData_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.motionDataEntrypted_ = motionDataEntrypted_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.firmwareVersion_ = firmwareVersion_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand) {
          return mergeFrom((com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand other) {
        if (other == com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000004;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasAccountId()) {
          bitField0_ |= 0x00000008;
          accountId_ = other.accountId_;
          onChanged();
        }
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasWifiName()) {
          bitField0_ |= 0x00000020;
          wifiName_ = other.wifiName_;
          onChanged();
        }
        if (other.hasWifiSSID()) {
          bitField0_ |= 0x00000040;
          wifiSSID_ = other.wifiSSID_;
          onChanged();
        }
        if (other.hasWifiPassword()) {
          bitField0_ |= 0x00000080;
          wifiPassword_ = other.wifiPassword_;
          onChanged();
        }
        if (other.hasBatteryLevel()) {
          setBatteryLevel(other.getBatteryLevel());
        }
        if (other.hasUptime()) {
          setUptime(other.getUptime());
        }
        if (other.hasMotionData()) {
          setMotionData(other.getMotionData());
        }
        if (other.hasMotionDataEntrypted()) {
          setMotionDataEntrypted(other.getMotionDataEntrypted());
        }
        if (other.hasFirmwareVersion()) {
          setFirmwareVersion(other.getFirmwareVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 version = 1;
      private int version_ ;
      /**
       * <code>required int32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // required .hello.MorpheusCommand.CommandType type = 2;
      private com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.CommandType type_ = com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.CommandType.MORPHEUS_COMMAND_SET_TIME;
      /**
       * <code>required .hello.MorpheusCommand.CommandType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .hello.MorpheusCommand.CommandType type = 2;</code>
       */
      public com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.CommandType getType() {
        return type_;
      }
      /**
       * <code>required .hello.MorpheusCommand.CommandType type = 2;</code>
       */
      public Builder setType(com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .hello.MorpheusCommand.CommandType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = com.hello.suripu.api.ble.MorpheusBle.MorpheusCommand.CommandType.MORPHEUS_COMMAND_SET_TIME;
        onChanged();
        return this;
      }

      // optional string deviceId = 3;
      private java.lang.Object deviceId_ = "";
      /**
       * <code>optional string deviceId = 3;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string deviceId = 3;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deviceId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deviceId = 3;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceId = 3;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceId = 3;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceId_ = value;
        onChanged();
        return this;
      }

      // optional string accountId = 4;
      private java.lang.Object accountId_ = "";
      /**
       * <code>optional string accountId = 4;</code>
       *
       * <pre>
       * Used by MORPHEUS_COMMAND_PAIRE_PILL
       * </pre>
       */
      public boolean hasAccountId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string accountId = 4;</code>
       *
       * <pre>
       * Used by MORPHEUS_COMMAND_PAIRE_PILL
       * </pre>
       */
      public java.lang.String getAccountId() {
        java.lang.Object ref = accountId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          accountId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string accountId = 4;</code>
       *
       * <pre>
       * Used by MORPHEUS_COMMAND_PAIRE_PILL
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAccountIdBytes() {
        java.lang.Object ref = accountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string accountId = 4;</code>
       *
       * <pre>
       * Used by MORPHEUS_COMMAND_PAIRE_PILL
       * </pre>
       */
      public Builder setAccountId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        accountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string accountId = 4;</code>
       *
       * <pre>
       * Used by MORPHEUS_COMMAND_PAIRE_PILL
       * </pre>
       */
      public Builder clearAccountId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        accountId_ = getDefaultInstance().getAccountId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string accountId = 4;</code>
       *
       * <pre>
       * Used by MORPHEUS_COMMAND_PAIRE_PILL
       * </pre>
       */
      public Builder setAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        accountId_ = value;
        onChanged();
        return this;
      }

      // optional .hello.ErrorType error = 5;
      private com.hello.suripu.api.ble.MorpheusBle.ErrorType error_ = com.hello.suripu.api.ble.MorpheusBle.ErrorType.TIME_OUT;
      /**
       * <code>optional .hello.ErrorType error = 5;</code>
       *
       * <pre>
       * MORPHEUS_COMMAND_ERROR
       * </pre>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .hello.ErrorType error = 5;</code>
       *
       * <pre>
       * MORPHEUS_COMMAND_ERROR
       * </pre>
       */
      public com.hello.suripu.api.ble.MorpheusBle.ErrorType getError() {
        return error_;
      }
      /**
       * <code>optional .hello.ErrorType error = 5;</code>
       *
       * <pre>
       * MORPHEUS_COMMAND_ERROR
       * </pre>
       */
      public Builder setError(com.hello.suripu.api.ble.MorpheusBle.ErrorType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .hello.ErrorType error = 5;</code>
       *
       * <pre>
       * MORPHEUS_COMMAND_ERROR
       * </pre>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000010);
        error_ = com.hello.suripu.api.ble.MorpheusBle.ErrorType.TIME_OUT;
        onChanged();
        return this;
      }

      // optional string wifiName = 6;
      private java.lang.Object wifiName_ = "";
      /**
       * <code>optional string wifiName = 6;</code>
       */
      public boolean hasWifiName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string wifiName = 6;</code>
       */
      public java.lang.String getWifiName() {
        java.lang.Object ref = wifiName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          wifiName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string wifiName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getWifiNameBytes() {
        java.lang.Object ref = wifiName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wifiName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string wifiName = 6;</code>
       */
      public Builder setWifiName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        wifiName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string wifiName = 6;</code>
       */
      public Builder clearWifiName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        wifiName_ = getDefaultInstance().getWifiName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string wifiName = 6;</code>
       */
      public Builder setWifiNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        wifiName_ = value;
        onChanged();
        return this;
      }

      // optional string wifiSSID = 7;
      private java.lang.Object wifiSSID_ = "";
      /**
       * <code>optional string wifiSSID = 7;</code>
       */
      public boolean hasWifiSSID() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string wifiSSID = 7;</code>
       */
      public java.lang.String getWifiSSID() {
        java.lang.Object ref = wifiSSID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          wifiSSID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string wifiSSID = 7;</code>
       */
      public com.google.protobuf.ByteString
          getWifiSSIDBytes() {
        java.lang.Object ref = wifiSSID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wifiSSID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string wifiSSID = 7;</code>
       */
      public Builder setWifiSSID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        wifiSSID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string wifiSSID = 7;</code>
       */
      public Builder clearWifiSSID() {
        bitField0_ = (bitField0_ & ~0x00000040);
        wifiSSID_ = getDefaultInstance().getWifiSSID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string wifiSSID = 7;</code>
       */
      public Builder setWifiSSIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        wifiSSID_ = value;
        onChanged();
        return this;
      }

      // optional string wifiPassword = 8;
      private java.lang.Object wifiPassword_ = "";
      /**
       * <code>optional string wifiPassword = 8;</code>
       */
      public boolean hasWifiPassword() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string wifiPassword = 8;</code>
       */
      public java.lang.String getWifiPassword() {
        java.lang.Object ref = wifiPassword_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          wifiPassword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string wifiPassword = 8;</code>
       */
      public com.google.protobuf.ByteString
          getWifiPasswordBytes() {
        java.lang.Object ref = wifiPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wifiPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string wifiPassword = 8;</code>
       */
      public Builder setWifiPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        wifiPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string wifiPassword = 8;</code>
       */
      public Builder clearWifiPassword() {
        bitField0_ = (bitField0_ & ~0x00000080);
        wifiPassword_ = getDefaultInstance().getWifiPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string wifiPassword = 8;</code>
       */
      public Builder setWifiPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        wifiPassword_ = value;
        onChanged();
        return this;
      }

      // optional int32 batteryLevel = 9;
      private int batteryLevel_ ;
      /**
       * <code>optional int32 batteryLevel = 9;</code>
       */
      public boolean hasBatteryLevel() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 batteryLevel = 9;</code>
       */
      public int getBatteryLevel() {
        return batteryLevel_;
      }
      /**
       * <code>optional int32 batteryLevel = 9;</code>
       */
      public Builder setBatteryLevel(int value) {
        bitField0_ |= 0x00000100;
        batteryLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 batteryLevel = 9;</code>
       */
      public Builder clearBatteryLevel() {
        bitField0_ = (bitField0_ & ~0x00000100);
        batteryLevel_ = 0;
        onChanged();
        return this;
      }

      // optional int32 uptime = 10;
      private int uptime_ ;
      /**
       * <code>optional int32 uptime = 10;</code>
       */
      public boolean hasUptime() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 uptime = 10;</code>
       */
      public int getUptime() {
        return uptime_;
      }
      /**
       * <code>optional int32 uptime = 10;</code>
       */
      public Builder setUptime(int value) {
        bitField0_ |= 0x00000200;
        uptime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uptime = 10;</code>
       */
      public Builder clearUptime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        uptime_ = 0;
        onChanged();
        return this;
      }

      // optional int32 motionData = 11;
      private int motionData_ ;
      /**
       * <code>optional int32 motionData = 11;</code>
       */
      public boolean hasMotionData() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 motionData = 11;</code>
       */
      public int getMotionData() {
        return motionData_;
      }
      /**
       * <code>optional int32 motionData = 11;</code>
       */
      public Builder setMotionData(int value) {
        bitField0_ |= 0x00000400;
        motionData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 motionData = 11;</code>
       */
      public Builder clearMotionData() {
        bitField0_ = (bitField0_ & ~0x00000400);
        motionData_ = 0;
        onChanged();
        return this;
      }

      // optional bytes motionDataEntrypted = 12;
      private com.google.protobuf.ByteString motionDataEntrypted_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes motionDataEntrypted = 12;</code>
       */
      public boolean hasMotionDataEntrypted() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional bytes motionDataEntrypted = 12;</code>
       */
      public com.google.protobuf.ByteString getMotionDataEntrypted() {
        return motionDataEntrypted_;
      }
      /**
       * <code>optional bytes motionDataEntrypted = 12;</code>
       */
      public Builder setMotionDataEntrypted(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        motionDataEntrypted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes motionDataEntrypted = 12;</code>
       */
      public Builder clearMotionDataEntrypted() {
        bitField0_ = (bitField0_ & ~0x00000800);
        motionDataEntrypted_ = getDefaultInstance().getMotionDataEntrypted();
        onChanged();
        return this;
      }

      // optional int32 firmwareVersion = 13;
      private int firmwareVersion_ ;
      /**
       * <code>optional int32 firmwareVersion = 13;</code>
       */
      public boolean hasFirmwareVersion() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int32 firmwareVersion = 13;</code>
       */
      public int getFirmwareVersion() {
        return firmwareVersion_;
      }
      /**
       * <code>optional int32 firmwareVersion = 13;</code>
       */
      public Builder setFirmwareVersion(int value) {
        bitField0_ |= 0x00001000;
        firmwareVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 firmwareVersion = 13;</code>
       */
      public Builder clearFirmwareVersion() {
        bitField0_ = (bitField0_ & ~0x00001000);
        firmwareVersion_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hello.MorpheusCommand)
    }

    static {
      defaultInstance = new MorpheusCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hello.MorpheusCommand)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_MorpheusCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hello_MorpheusCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7suripu-api/src/main/resources/protos/m" +
      "orpheus_ble.proto\022\005hello\"\246\010\n\017MorpheusCom" +
      "mand\022\017\n\007version\030\001 \002(\005\0220\n\004type\030\002 \002(\0162\".he" +
      "llo.MorpheusCommand.CommandType\022\020\n\010devic" +
      "eId\030\003 \001(\t\022\021\n\taccountId\030\004 \001(\t\022\037\n\005error\030\005 " +
      "\001(\0162\020.hello.ErrorType\022\020\n\010wifiName\030\006 \001(\t\022" +
      "\020\n\010wifiSSID\030\007 \001(\t\022\024\n\014wifiPassword\030\010 \001(\t\022" +
      "\024\n\014batteryLevel\030\t \001(\005\022\016\n\006uptime\030\n \001(\005\022\022\n" +
      "\nmotionData\030\013 \001(\005\022\033\n\023motionDataEntrypted" +
      "\030\014 \001(\014\022\027\n\017firmwareVersion\030\r \001(\005\"\337\005\n\013Comm",
      "andType\022\035\n\031MORPHEUS_COMMAND_SET_TIME\020\000\022\035" +
      "\n\031MORPHEUS_COMMAND_GET_TIME\020\001\022&\n\"MORPHEU" +
      "S_COMMAND_SET_WIFI_ENDPOINT\020\002\022&\n\"MORPHEU" +
      "S_COMMAND_GET_WIFI_ENDPOINT\020\003\022\037\n\033MORPHEU" +
      "S_COMMAND_SET_ALARMS\020\004\022\037\n\033MORPHEUS_COMMA" +
      "ND_GET_ALARMS\020\005\022+\n\'MORPHEUS_COMMAND_SWIT" +
      "CH_TO_PAIRING_MODE\020\006\022*\n&MORPHEUS_COMMAND" +
      "_SWITCH_TO_NORMAL_MODE\020\007\022#\n\037MORPHEUS_COM" +
      "MAND_START_WIFISCAN\020\010\022\"\n\036MORPHEUS_COMMAN" +
      "D_STOP_WIFISCAN\020\t\022\"\n\036MORPHEUS_COMMAND_GE",
      "T_DEVICE_ID\020\n\022(\n$MORPHEUS_COMMAND_EREASE" +
      "_PAIRED_PHONE\020\013\022\036\n\032MORPHEUS_COMMAND_PAIR" +
      "_PILL\020\014\022\032\n\026MORPHEUS_COMMAND_ERROR\020\r\022\037\n\033M" +
      "ORPHEUS_COMMAND_PAIR_SENSE\020\016\022 \n\034MORPHEUS" +
      "_COMMAND_UNPAIR_PILL\020\017\022\'\n#MORPHEUS_COMMA" +
      "ND_MORPHEUS_DFU_BEGIN\020\020\022\036\n\032MORPHEUS_COMM" +
      "AND_PILL_DATA\020\021\022#\n\037MORPHEUS_COMMAND_PILL" +
      "_HEARTBEAT\020\022\022#\n\037MORPHEUS_COMMAND_PILL_DF" +
      "U_BEGIN\020\023*\257\001\n\tErrorType\022\014\n\010TIME_OUT\020\000\022\021\n" +
      "\rNETWORK_ERROR\020\001\022\031\n\025DEVICE_ALREADY_PAIRE",
      "D\020\002\022\027\n\023INTERNAL_DATA_ERROR\020\003\022\030\n\024DEVICE_D" +
      "ATABASE_FULL\020\004\022\024\n\020DEVICE_NO_MEMORY\020\005\022\035\n\031" +
      "INTERNAL_OPERATION_FAILED\020\006B\032\n\030com.hello" +
      ".suripu.api.ble"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hello_MorpheusCommand_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hello_MorpheusCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hello_MorpheusCommand_descriptor,
              new java.lang.String[] { "Version", "Type", "DeviceId", "AccountId", "Error", "WifiName", "WifiSSID", "WifiPassword", "BatteryLevel", "Uptime", "MotionData", "MotionDataEntrypted", "FirmwareVersion", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
