// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: encode.proto

package com.hello.suripu.api.audio;

public final class EncodeProtos {
  private EncodeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AudioFileMetadataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string device_id = 1;
    /**
     * <code>optional string device_id = 1;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>optional string device_id = 1;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>optional string device_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    // optional string s3_url = 2;
    /**
     * <code>optional string s3_url = 2;</code>
     */
    boolean hasS3Url();
    /**
     * <code>optional string s3_url = 2;</code>
     */
    java.lang.String getS3Url();
    /**
     * <code>optional string s3_url = 2;</code>
     */
    com.google.protobuf.ByteString
        getS3UrlBytes();

    // optional int32 unix_time = 3;
    /**
     * <code>optional int32 unix_time = 3;</code>
     */
    boolean hasUnixTime();
    /**
     * <code>optional int32 unix_time = 3;</code>
     */
    int getUnixTime();
  }
  /**
   * Protobuf type {@code AudioFileMetadata}
   */
  public static final class AudioFileMetadata extends
      com.google.protobuf.GeneratedMessage
      implements AudioFileMetadataOrBuilder {
    // Use AudioFileMetadata.newBuilder() to construct.
    private AudioFileMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AudioFileMetadata(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AudioFileMetadata defaultInstance;
    public static AudioFileMetadata getDefaultInstance() {
      return defaultInstance;
    }

    public AudioFileMetadata getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AudioFileMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              s3Url_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              unixTime_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hello.suripu.api.audio.EncodeProtos.internal_static_AudioFileMetadata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hello.suripu.api.audio.EncodeProtos.internal_static_AudioFileMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata.class, com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata.Builder.class);
    }

    public static com.google.protobuf.Parser<AudioFileMetadata> PARSER =
        new com.google.protobuf.AbstractParser<AudioFileMetadata>() {
      public AudioFileMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AudioFileMetadata(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AudioFileMetadata> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string device_id = 1;
    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private java.lang.Object deviceId_;
    /**
     * <code>optional string device_id = 1;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string device_id = 1;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string s3_url = 2;
    public static final int S3_URL_FIELD_NUMBER = 2;
    private java.lang.Object s3Url_;
    /**
     * <code>optional string s3_url = 2;</code>
     */
    public boolean hasS3Url() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string s3_url = 2;</code>
     */
    public java.lang.String getS3Url() {
      java.lang.Object ref = s3Url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s3Url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s3_url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getS3UrlBytes() {
      java.lang.Object ref = s3Url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s3Url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 unix_time = 3;
    public static final int UNIX_TIME_FIELD_NUMBER = 3;
    private int unixTime_;
    /**
     * <code>optional int32 unix_time = 3;</code>
     */
    public boolean hasUnixTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 unix_time = 3;</code>
     */
    public int getUnixTime() {
      return unixTime_;
    }

    private void initFields() {
      deviceId_ = "";
      s3Url_ = "";
      unixTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getS3UrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, unixTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getS3UrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, unixTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AudioFileMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hello.suripu.api.audio.EncodeProtos.internal_static_AudioFileMetadata_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hello.suripu.api.audio.EncodeProtos.internal_static_AudioFileMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata.class, com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata.Builder.class);
      }

      // Construct using com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        s3Url_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        unixTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hello.suripu.api.audio.EncodeProtos.internal_static_AudioFileMetadata_descriptor;
      }

      public com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata getDefaultInstanceForType() {
        return com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata.getDefaultInstance();
      }

      public com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata build() {
        com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata buildPartial() {
        com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata result = new com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.s3Url_ = s3Url_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.unixTime_ = unixTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata) {
          return mergeFrom((com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata other) {
        if (other == com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000001;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasS3Url()) {
          bitField0_ |= 0x00000002;
          s3Url_ = other.s3Url_;
          onChanged();
        }
        if (other.hasUnixTime()) {
          setUnixTime(other.getUnixTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hello.suripu.api.audio.EncodeProtos.AudioFileMetadata) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string device_id = 1;
      private java.lang.Object deviceId_ = "";
      /**
       * <code>optional string device_id = 1;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string device_id = 1;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_id = 1;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 1;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }

      // optional string s3_url = 2;
      private java.lang.Object s3Url_ = "";
      /**
       * <code>optional string s3_url = 2;</code>
       */
      public boolean hasS3Url() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string s3_url = 2;</code>
       */
      public java.lang.String getS3Url() {
        java.lang.Object ref = s3Url_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          s3Url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s3_url = 2;</code>
       */
      public com.google.protobuf.ByteString
          getS3UrlBytes() {
        java.lang.Object ref = s3Url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s3Url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s3_url = 2;</code>
       */
      public Builder setS3Url(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s3Url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s3_url = 2;</code>
       */
      public Builder clearS3Url() {
        bitField0_ = (bitField0_ & ~0x00000002);
        s3Url_ = getDefaultInstance().getS3Url();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s3_url = 2;</code>
       */
      public Builder setS3UrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s3Url_ = value;
        onChanged();
        return this;
      }

      // optional int32 unix_time = 3;
      private int unixTime_ ;
      /**
       * <code>optional int32 unix_time = 3;</code>
       */
      public boolean hasUnixTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 unix_time = 3;</code>
       */
      public int getUnixTime() {
        return unixTime_;
      }
      /**
       * <code>optional int32 unix_time = 3;</code>
       */
      public Builder setUnixTime(int value) {
        bitField0_ |= 0x00000004;
        unixTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 unix_time = 3;</code>
       */
      public Builder clearUnixTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        unixTime_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AudioFileMetadata)
    }

    static {
      defaultInstance = new AudioFileMetadata(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AudioFileMetadata)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AudioFileMetadata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AudioFileMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014encode.proto\"I\n\021AudioFileMetadata\022\021\n\td" +
      "evice_id\030\001 \001(\t\022\016\n\006s3_url\030\002 \001(\t\022\021\n\tunix_t" +
      "ime\030\003 \001(\005B*\n\032com.hello.suripu.api.audioB" +
      "\014EncodeProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_AudioFileMetadata_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_AudioFileMetadata_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AudioFileMetadata_descriptor,
              new java.lang.String[] { "DeviceId", "S3Url", "UnixTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
