// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cleanup.proto

package com.hello.suripu.api.cleanup;

public final class CleanUp {
  private CleanUp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CleanupMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CleanupMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string requester = 1;</code>
     */
    boolean hasRequester();
    /**
     * <code>required string requester = 1;</code>
     */
    java.lang.String getRequester();
    /**
     * <code>required string requester = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequesterBytes();

    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    long getTimestamp();

    /**
     * <code>optional .DisableAccount disable_account = 3;</code>
     */
    boolean hasDisableAccount();
    /**
     * <code>optional .DisableAccount disable_account = 3;</code>
     */
    com.hello.suripu.api.cleanup.CleanUp.DisableAccount getDisableAccount();
    /**
     * <code>optional .DisableAccount disable_account = 3;</code>
     */
    com.hello.suripu.api.cleanup.CleanUp.DisableAccountOrBuilder getDisableAccountOrBuilder();

    /**
     * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
     */
    boolean hasExpireOauthTokens();
    /**
     * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
     */
    com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens getExpireOauthTokens();
    /**
     * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
     */
    com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokensOrBuilder getExpireOauthTokensOrBuilder();

    /**
     * <code>optional .RemoveExpansions remove_expansions = 5;</code>
     */
    boolean hasRemoveExpansions();
    /**
     * <code>optional .RemoveExpansions remove_expansions = 5;</code>
     */
    com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions getRemoveExpansions();
    /**
     * <code>optional .RemoveExpansions remove_expansions = 5;</code>
     */
    com.hello.suripu.api.cleanup.CleanUp.RemoveExpansionsOrBuilder getRemoveExpansionsOrBuilder();
  }
  /**
   * Protobuf type {@code CleanupMessage}
   */
  public static final class CleanupMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CleanupMessage)
      CleanupMessageOrBuilder {
    // Use CleanupMessage.newBuilder() to construct.
    private CleanupMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CleanupMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CleanupMessage defaultInstance;
    public static CleanupMessage getDefaultInstance() {
      return defaultInstance;
    }

    public CleanupMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CleanupMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              requester_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 26: {
              com.hello.suripu.api.cleanup.CleanUp.DisableAccount.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = disableAccount_.toBuilder();
              }
              disableAccount_ = input.readMessage(com.hello.suripu.api.cleanup.CleanUp.DisableAccount.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(disableAccount_);
                disableAccount_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = expireOauthTokens_.toBuilder();
              }
              expireOauthTokens_ = input.readMessage(com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(expireOauthTokens_);
                expireOauthTokens_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = removeExpansions_.toBuilder();
              }
              removeExpansions_ = input.readMessage(com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(removeExpansions_);
                removeExpansions_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hello.suripu.api.cleanup.CleanUp.internal_static_CleanupMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hello.suripu.api.cleanup.CleanUp.internal_static_CleanupMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hello.suripu.api.cleanup.CleanUp.CleanupMessage.class, com.hello.suripu.api.cleanup.CleanUp.CleanupMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<CleanupMessage> PARSER =
        new com.google.protobuf.AbstractParser<CleanupMessage>() {
      public CleanupMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CleanupMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CleanupMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int REQUESTER_FIELD_NUMBER = 1;
    private java.lang.Object requester_;
    /**
     * <code>required string requester = 1;</code>
     */
    public boolean hasRequester() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string requester = 1;</code>
     */
    public java.lang.String getRequester() {
      java.lang.Object ref = requester_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requester_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string requester = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequesterBytes() {
      java.lang.Object ref = requester_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requester_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int DISABLE_ACCOUNT_FIELD_NUMBER = 3;
    private com.hello.suripu.api.cleanup.CleanUp.DisableAccount disableAccount_;
    /**
     * <code>optional .DisableAccount disable_account = 3;</code>
     */
    public boolean hasDisableAccount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .DisableAccount disable_account = 3;</code>
     */
    public com.hello.suripu.api.cleanup.CleanUp.DisableAccount getDisableAccount() {
      return disableAccount_;
    }
    /**
     * <code>optional .DisableAccount disable_account = 3;</code>
     */
    public com.hello.suripu.api.cleanup.CleanUp.DisableAccountOrBuilder getDisableAccountOrBuilder() {
      return disableAccount_;
    }

    public static final int EXPIRE_OAUTH_TOKENS_FIELD_NUMBER = 4;
    private com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens expireOauthTokens_;
    /**
     * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
     */
    public boolean hasExpireOauthTokens() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
     */
    public com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens getExpireOauthTokens() {
      return expireOauthTokens_;
    }
    /**
     * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
     */
    public com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokensOrBuilder getExpireOauthTokensOrBuilder() {
      return expireOauthTokens_;
    }

    public static final int REMOVE_EXPANSIONS_FIELD_NUMBER = 5;
    private com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions removeExpansions_;
    /**
     * <code>optional .RemoveExpansions remove_expansions = 5;</code>
     */
    public boolean hasRemoveExpansions() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .RemoveExpansions remove_expansions = 5;</code>
     */
    public com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions getRemoveExpansions() {
      return removeExpansions_;
    }
    /**
     * <code>optional .RemoveExpansions remove_expansions = 5;</code>
     */
    public com.hello.suripu.api.cleanup.CleanUp.RemoveExpansionsOrBuilder getRemoveExpansionsOrBuilder() {
      return removeExpansions_;
    }

    private void initFields() {
      requester_ = "";
      timestamp_ = 0L;
      disableAccount_ = com.hello.suripu.api.cleanup.CleanUp.DisableAccount.getDefaultInstance();
      expireOauthTokens_ = com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.getDefaultInstance();
      removeExpansions_ = com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRequester()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasDisableAccount()) {
        if (!getDisableAccount().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasExpireOauthTokens()) {
        if (!getExpireOauthTokens().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasRemoveExpansions()) {
        if (!getRemoveExpansions().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRequesterBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, disableAccount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, expireOauthTokens_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, removeExpansions_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRequesterBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, disableAccount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, expireOauthTokens_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, removeExpansions_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hello.suripu.api.cleanup.CleanUp.CleanupMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.CleanupMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.CleanupMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.CleanupMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.CleanupMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.CleanupMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.CleanupMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.CleanupMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.CleanupMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.CleanupMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hello.suripu.api.cleanup.CleanUp.CleanupMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CleanupMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CleanupMessage)
        com.hello.suripu.api.cleanup.CleanUp.CleanupMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hello.suripu.api.cleanup.CleanUp.internal_static_CleanupMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hello.suripu.api.cleanup.CleanUp.internal_static_CleanupMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hello.suripu.api.cleanup.CleanUp.CleanupMessage.class, com.hello.suripu.api.cleanup.CleanUp.CleanupMessage.Builder.class);
      }

      // Construct using com.hello.suripu.api.cleanup.CleanUp.CleanupMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDisableAccountFieldBuilder();
          getExpireOauthTokensFieldBuilder();
          getRemoveExpansionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        requester_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (disableAccountBuilder_ == null) {
          disableAccount_ = com.hello.suripu.api.cleanup.CleanUp.DisableAccount.getDefaultInstance();
        } else {
          disableAccountBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (expireOauthTokensBuilder_ == null) {
          expireOauthTokens_ = com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.getDefaultInstance();
        } else {
          expireOauthTokensBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (removeExpansionsBuilder_ == null) {
          removeExpansions_ = com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.getDefaultInstance();
        } else {
          removeExpansionsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hello.suripu.api.cleanup.CleanUp.internal_static_CleanupMessage_descriptor;
      }

      public com.hello.suripu.api.cleanup.CleanUp.CleanupMessage getDefaultInstanceForType() {
        return com.hello.suripu.api.cleanup.CleanUp.CleanupMessage.getDefaultInstance();
      }

      public com.hello.suripu.api.cleanup.CleanUp.CleanupMessage build() {
        com.hello.suripu.api.cleanup.CleanUp.CleanupMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hello.suripu.api.cleanup.CleanUp.CleanupMessage buildPartial() {
        com.hello.suripu.api.cleanup.CleanUp.CleanupMessage result = new com.hello.suripu.api.cleanup.CleanUp.CleanupMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requester_ = requester_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (disableAccountBuilder_ == null) {
          result.disableAccount_ = disableAccount_;
        } else {
          result.disableAccount_ = disableAccountBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (expireOauthTokensBuilder_ == null) {
          result.expireOauthTokens_ = expireOauthTokens_;
        } else {
          result.expireOauthTokens_ = expireOauthTokensBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (removeExpansionsBuilder_ == null) {
          result.removeExpansions_ = removeExpansions_;
        } else {
          result.removeExpansions_ = removeExpansionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hello.suripu.api.cleanup.CleanUp.CleanupMessage) {
          return mergeFrom((com.hello.suripu.api.cleanup.CleanUp.CleanupMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hello.suripu.api.cleanup.CleanUp.CleanupMessage other) {
        if (other == com.hello.suripu.api.cleanup.CleanUp.CleanupMessage.getDefaultInstance()) return this;
        if (other.hasRequester()) {
          bitField0_ |= 0x00000001;
          requester_ = other.requester_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasDisableAccount()) {
          mergeDisableAccount(other.getDisableAccount());
        }
        if (other.hasExpireOauthTokens()) {
          mergeExpireOauthTokens(other.getExpireOauthTokens());
        }
        if (other.hasRemoveExpansions()) {
          mergeRemoveExpansions(other.getRemoveExpansions());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequester()) {
          
          return false;
        }
        if (hasDisableAccount()) {
          if (!getDisableAccount().isInitialized()) {
            
            return false;
          }
        }
        if (hasExpireOauthTokens()) {
          if (!getExpireOauthTokens().isInitialized()) {
            
            return false;
          }
        }
        if (hasRemoveExpansions()) {
          if (!getRemoveExpansions().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hello.suripu.api.cleanup.CleanUp.CleanupMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hello.suripu.api.cleanup.CleanUp.CleanupMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object requester_ = "";
      /**
       * <code>required string requester = 1;</code>
       */
      public boolean hasRequester() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string requester = 1;</code>
       */
      public java.lang.String getRequester() {
        java.lang.Object ref = requester_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requester_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string requester = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequesterBytes() {
        java.lang.Object ref = requester_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requester_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string requester = 1;</code>
       */
      public Builder setRequester(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requester_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string requester = 1;</code>
       */
      public Builder clearRequester() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requester_ = getDefaultInstance().getRequester();
        onChanged();
        return this;
      }
      /**
       * <code>required string requester = 1;</code>
       */
      public Builder setRequesterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requester_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.hello.suripu.api.cleanup.CleanUp.DisableAccount disableAccount_ = com.hello.suripu.api.cleanup.CleanUp.DisableAccount.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.hello.suripu.api.cleanup.CleanUp.DisableAccount, com.hello.suripu.api.cleanup.CleanUp.DisableAccount.Builder, com.hello.suripu.api.cleanup.CleanUp.DisableAccountOrBuilder> disableAccountBuilder_;
      /**
       * <code>optional .DisableAccount disable_account = 3;</code>
       */
      public boolean hasDisableAccount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .DisableAccount disable_account = 3;</code>
       */
      public com.hello.suripu.api.cleanup.CleanUp.DisableAccount getDisableAccount() {
        if (disableAccountBuilder_ == null) {
          return disableAccount_;
        } else {
          return disableAccountBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .DisableAccount disable_account = 3;</code>
       */
      public Builder setDisableAccount(com.hello.suripu.api.cleanup.CleanUp.DisableAccount value) {
        if (disableAccountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          disableAccount_ = value;
          onChanged();
        } else {
          disableAccountBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .DisableAccount disable_account = 3;</code>
       */
      public Builder setDisableAccount(
          com.hello.suripu.api.cleanup.CleanUp.DisableAccount.Builder builderForValue) {
        if (disableAccountBuilder_ == null) {
          disableAccount_ = builderForValue.build();
          onChanged();
        } else {
          disableAccountBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .DisableAccount disable_account = 3;</code>
       */
      public Builder mergeDisableAccount(com.hello.suripu.api.cleanup.CleanUp.DisableAccount value) {
        if (disableAccountBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              disableAccount_ != com.hello.suripu.api.cleanup.CleanUp.DisableAccount.getDefaultInstance()) {
            disableAccount_ =
              com.hello.suripu.api.cleanup.CleanUp.DisableAccount.newBuilder(disableAccount_).mergeFrom(value).buildPartial();
          } else {
            disableAccount_ = value;
          }
          onChanged();
        } else {
          disableAccountBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .DisableAccount disable_account = 3;</code>
       */
      public Builder clearDisableAccount() {
        if (disableAccountBuilder_ == null) {
          disableAccount_ = com.hello.suripu.api.cleanup.CleanUp.DisableAccount.getDefaultInstance();
          onChanged();
        } else {
          disableAccountBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .DisableAccount disable_account = 3;</code>
       */
      public com.hello.suripu.api.cleanup.CleanUp.DisableAccount.Builder getDisableAccountBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getDisableAccountFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .DisableAccount disable_account = 3;</code>
       */
      public com.hello.suripu.api.cleanup.CleanUp.DisableAccountOrBuilder getDisableAccountOrBuilder() {
        if (disableAccountBuilder_ != null) {
          return disableAccountBuilder_.getMessageOrBuilder();
        } else {
          return disableAccount_;
        }
      }
      /**
       * <code>optional .DisableAccount disable_account = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.hello.suripu.api.cleanup.CleanUp.DisableAccount, com.hello.suripu.api.cleanup.CleanUp.DisableAccount.Builder, com.hello.suripu.api.cleanup.CleanUp.DisableAccountOrBuilder> 
          getDisableAccountFieldBuilder() {
        if (disableAccountBuilder_ == null) {
          disableAccountBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.hello.suripu.api.cleanup.CleanUp.DisableAccount, com.hello.suripu.api.cleanup.CleanUp.DisableAccount.Builder, com.hello.suripu.api.cleanup.CleanUp.DisableAccountOrBuilder>(
                  getDisableAccount(),
                  getParentForChildren(),
                  isClean());
          disableAccount_ = null;
        }
        return disableAccountBuilder_;
      }

      private com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens expireOauthTokens_ = com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens, com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.Builder, com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokensOrBuilder> expireOauthTokensBuilder_;
      /**
       * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
       */
      public boolean hasExpireOauthTokens() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
       */
      public com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens getExpireOauthTokens() {
        if (expireOauthTokensBuilder_ == null) {
          return expireOauthTokens_;
        } else {
          return expireOauthTokensBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
       */
      public Builder setExpireOauthTokens(com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens value) {
        if (expireOauthTokensBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          expireOauthTokens_ = value;
          onChanged();
        } else {
          expireOauthTokensBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
       */
      public Builder setExpireOauthTokens(
          com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.Builder builderForValue) {
        if (expireOauthTokensBuilder_ == null) {
          expireOauthTokens_ = builderForValue.build();
          onChanged();
        } else {
          expireOauthTokensBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
       */
      public Builder mergeExpireOauthTokens(com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens value) {
        if (expireOauthTokensBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              expireOauthTokens_ != com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.getDefaultInstance()) {
            expireOauthTokens_ =
              com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.newBuilder(expireOauthTokens_).mergeFrom(value).buildPartial();
          } else {
            expireOauthTokens_ = value;
          }
          onChanged();
        } else {
          expireOauthTokensBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
       */
      public Builder clearExpireOauthTokens() {
        if (expireOauthTokensBuilder_ == null) {
          expireOauthTokens_ = com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.getDefaultInstance();
          onChanged();
        } else {
          expireOauthTokensBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
       */
      public com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.Builder getExpireOauthTokensBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getExpireOauthTokensFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
       */
      public com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokensOrBuilder getExpireOauthTokensOrBuilder() {
        if (expireOauthTokensBuilder_ != null) {
          return expireOauthTokensBuilder_.getMessageOrBuilder();
        } else {
          return expireOauthTokens_;
        }
      }
      /**
       * <code>optional .ExpireOAuthTokens expire_oauth_tokens = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens, com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.Builder, com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokensOrBuilder> 
          getExpireOauthTokensFieldBuilder() {
        if (expireOauthTokensBuilder_ == null) {
          expireOauthTokensBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens, com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.Builder, com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokensOrBuilder>(
                  getExpireOauthTokens(),
                  getParentForChildren(),
                  isClean());
          expireOauthTokens_ = null;
        }
        return expireOauthTokensBuilder_;
      }

      private com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions removeExpansions_ = com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions, com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.Builder, com.hello.suripu.api.cleanup.CleanUp.RemoveExpansionsOrBuilder> removeExpansionsBuilder_;
      /**
       * <code>optional .RemoveExpansions remove_expansions = 5;</code>
       */
      public boolean hasRemoveExpansions() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .RemoveExpansions remove_expansions = 5;</code>
       */
      public com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions getRemoveExpansions() {
        if (removeExpansionsBuilder_ == null) {
          return removeExpansions_;
        } else {
          return removeExpansionsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .RemoveExpansions remove_expansions = 5;</code>
       */
      public Builder setRemoveExpansions(com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions value) {
        if (removeExpansionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          removeExpansions_ = value;
          onChanged();
        } else {
          removeExpansionsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .RemoveExpansions remove_expansions = 5;</code>
       */
      public Builder setRemoveExpansions(
          com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.Builder builderForValue) {
        if (removeExpansionsBuilder_ == null) {
          removeExpansions_ = builderForValue.build();
          onChanged();
        } else {
          removeExpansionsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .RemoveExpansions remove_expansions = 5;</code>
       */
      public Builder mergeRemoveExpansions(com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions value) {
        if (removeExpansionsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              removeExpansions_ != com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.getDefaultInstance()) {
            removeExpansions_ =
              com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.newBuilder(removeExpansions_).mergeFrom(value).buildPartial();
          } else {
            removeExpansions_ = value;
          }
          onChanged();
        } else {
          removeExpansionsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .RemoveExpansions remove_expansions = 5;</code>
       */
      public Builder clearRemoveExpansions() {
        if (removeExpansionsBuilder_ == null) {
          removeExpansions_ = com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.getDefaultInstance();
          onChanged();
        } else {
          removeExpansionsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .RemoveExpansions remove_expansions = 5;</code>
       */
      public com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.Builder getRemoveExpansionsBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getRemoveExpansionsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .RemoveExpansions remove_expansions = 5;</code>
       */
      public com.hello.suripu.api.cleanup.CleanUp.RemoveExpansionsOrBuilder getRemoveExpansionsOrBuilder() {
        if (removeExpansionsBuilder_ != null) {
          return removeExpansionsBuilder_.getMessageOrBuilder();
        } else {
          return removeExpansions_;
        }
      }
      /**
       * <code>optional .RemoveExpansions remove_expansions = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions, com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.Builder, com.hello.suripu.api.cleanup.CleanUp.RemoveExpansionsOrBuilder> 
          getRemoveExpansionsFieldBuilder() {
        if (removeExpansionsBuilder_ == null) {
          removeExpansionsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions, com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.Builder, com.hello.suripu.api.cleanup.CleanUp.RemoveExpansionsOrBuilder>(
                  getRemoveExpansions(),
                  getParentForChildren(),
                  isClean());
          removeExpansions_ = null;
        }
        return removeExpansionsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:CleanupMessage)
    }

    static {
      defaultInstance = new CleanupMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CleanupMessage)
  }

  public interface DisableAccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DisableAccount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 account_id = 1;</code>
     */
    boolean hasAccountId();
    /**
     * <code>required int64 account_id = 1;</code>
     */
    long getAccountId();

    /**
     * <code>required string email = 2;</code>
     */
    boolean hasEmail();
    /**
     * <code>required string email = 2;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>required string email = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code DisableAccount}
   */
  public static final class DisableAccount extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DisableAccount)
      DisableAccountOrBuilder {
    // Use DisableAccount.newBuilder() to construct.
    private DisableAccount(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DisableAccount(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DisableAccount defaultInstance;
    public static DisableAccount getDefaultInstance() {
      return defaultInstance;
    }

    public DisableAccount getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DisableAccount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              accountId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              email_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hello.suripu.api.cleanup.CleanUp.internal_static_DisableAccount_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hello.suripu.api.cleanup.CleanUp.internal_static_DisableAccount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hello.suripu.api.cleanup.CleanUp.DisableAccount.class, com.hello.suripu.api.cleanup.CleanUp.DisableAccount.Builder.class);
    }

    public static com.google.protobuf.Parser<DisableAccount> PARSER =
        new com.google.protobuf.AbstractParser<DisableAccount>() {
      public DisableAccount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DisableAccount(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DisableAccount> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ACCOUNT_ID_FIELD_NUMBER = 1;
    private long accountId_;
    /**
     * <code>required int64 account_id = 1;</code>
     */
    public boolean hasAccountId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 account_id = 1;</code>
     */
    public long getAccountId() {
      return accountId_;
    }

    public static final int EMAIL_FIELD_NUMBER = 2;
    private java.lang.Object email_;
    /**
     * <code>required string email = 2;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string email = 2;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      accountId_ = 0L;
      email_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAccountId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, accountId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEmailBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, accountId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEmailBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hello.suripu.api.cleanup.CleanUp.DisableAccount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.DisableAccount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.DisableAccount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.DisableAccount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.DisableAccount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.DisableAccount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.DisableAccount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.DisableAccount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.DisableAccount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.DisableAccount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hello.suripu.api.cleanup.CleanUp.DisableAccount prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DisableAccount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DisableAccount)
        com.hello.suripu.api.cleanup.CleanUp.DisableAccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hello.suripu.api.cleanup.CleanUp.internal_static_DisableAccount_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hello.suripu.api.cleanup.CleanUp.internal_static_DisableAccount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hello.suripu.api.cleanup.CleanUp.DisableAccount.class, com.hello.suripu.api.cleanup.CleanUp.DisableAccount.Builder.class);
      }

      // Construct using com.hello.suripu.api.cleanup.CleanUp.DisableAccount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hello.suripu.api.cleanup.CleanUp.internal_static_DisableAccount_descriptor;
      }

      public com.hello.suripu.api.cleanup.CleanUp.DisableAccount getDefaultInstanceForType() {
        return com.hello.suripu.api.cleanup.CleanUp.DisableAccount.getDefaultInstance();
      }

      public com.hello.suripu.api.cleanup.CleanUp.DisableAccount build() {
        com.hello.suripu.api.cleanup.CleanUp.DisableAccount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hello.suripu.api.cleanup.CleanUp.DisableAccount buildPartial() {
        com.hello.suripu.api.cleanup.CleanUp.DisableAccount result = new com.hello.suripu.api.cleanup.CleanUp.DisableAccount(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountId_ = accountId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.email_ = email_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hello.suripu.api.cleanup.CleanUp.DisableAccount) {
          return mergeFrom((com.hello.suripu.api.cleanup.CleanUp.DisableAccount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hello.suripu.api.cleanup.CleanUp.DisableAccount other) {
        if (other == com.hello.suripu.api.cleanup.CleanUp.DisableAccount.getDefaultInstance()) return this;
        if (other.hasAccountId()) {
          setAccountId(other.getAccountId());
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000002;
          email_ = other.email_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccountId()) {
          
          return false;
        }
        if (!hasEmail()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hello.suripu.api.cleanup.CleanUp.DisableAccount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hello.suripu.api.cleanup.CleanUp.DisableAccount) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long accountId_ ;
      /**
       * <code>required int64 account_id = 1;</code>
       */
      public boolean hasAccountId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 account_id = 1;</code>
       */
      public long getAccountId() {
        return accountId_;
      }
      /**
       * <code>required int64 account_id = 1;</code>
       */
      public Builder setAccountId(long value) {
        bitField0_ |= 0x00000001;
        accountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 account_id = 1;</code>
       */
      public Builder clearAccountId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>required string email = 2;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string email = 2;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string email = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string email = 2;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 2;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 2;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DisableAccount)
    }

    static {
      defaultInstance = new DisableAccount(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DisableAccount)
  }

  public interface ExpireOAuthTokensOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ExpireOAuthTokens)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 account_id = 1;</code>
     */
    boolean hasAccountId();
    /**
     * <code>required int64 account_id = 1;</code>
     */
    long getAccountId();
  }
  /**
   * Protobuf type {@code ExpireOAuthTokens}
   */
  public static final class ExpireOAuthTokens extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ExpireOAuthTokens)
      ExpireOAuthTokensOrBuilder {
    // Use ExpireOAuthTokens.newBuilder() to construct.
    private ExpireOAuthTokens(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExpireOAuthTokens(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExpireOAuthTokens defaultInstance;
    public static ExpireOAuthTokens getDefaultInstance() {
      return defaultInstance;
    }

    public ExpireOAuthTokens getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExpireOAuthTokens(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              accountId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hello.suripu.api.cleanup.CleanUp.internal_static_ExpireOAuthTokens_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hello.suripu.api.cleanup.CleanUp.internal_static_ExpireOAuthTokens_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.class, com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.Builder.class);
    }

    public static com.google.protobuf.Parser<ExpireOAuthTokens> PARSER =
        new com.google.protobuf.AbstractParser<ExpireOAuthTokens>() {
      public ExpireOAuthTokens parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExpireOAuthTokens(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExpireOAuthTokens> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ACCOUNT_ID_FIELD_NUMBER = 1;
    private long accountId_;
    /**
     * <code>required int64 account_id = 1;</code>
     */
    public boolean hasAccountId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 account_id = 1;</code>
     */
    public long getAccountId() {
      return accountId_;
    }

    private void initFields() {
      accountId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAccountId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, accountId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, accountId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExpireOAuthTokens}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ExpireOAuthTokens)
        com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokensOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hello.suripu.api.cleanup.CleanUp.internal_static_ExpireOAuthTokens_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hello.suripu.api.cleanup.CleanUp.internal_static_ExpireOAuthTokens_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.class, com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.Builder.class);
      }

      // Construct using com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hello.suripu.api.cleanup.CleanUp.internal_static_ExpireOAuthTokens_descriptor;
      }

      public com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens getDefaultInstanceForType() {
        return com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.getDefaultInstance();
      }

      public com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens build() {
        com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens buildPartial() {
        com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens result = new com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountId_ = accountId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens) {
          return mergeFrom((com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens other) {
        if (other == com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens.getDefaultInstance()) return this;
        if (other.hasAccountId()) {
          setAccountId(other.getAccountId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccountId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hello.suripu.api.cleanup.CleanUp.ExpireOAuthTokens) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long accountId_ ;
      /**
       * <code>required int64 account_id = 1;</code>
       */
      public boolean hasAccountId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 account_id = 1;</code>
       */
      public long getAccountId() {
        return accountId_;
      }
      /**
       * <code>required int64 account_id = 1;</code>
       */
      public Builder setAccountId(long value) {
        bitField0_ |= 0x00000001;
        accountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 account_id = 1;</code>
       */
      public Builder clearAccountId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ExpireOAuthTokens)
    }

    static {
      defaultInstance = new ExpireOAuthTokens(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ExpireOAuthTokens)
  }

  public interface RemoveExpansionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RemoveExpansions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sense_id = 1;</code>
     */
    boolean hasSenseId();
    /**
     * <code>required string sense_id = 1;</code>
     */
    java.lang.String getSenseId();
    /**
     * <code>required string sense_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSenseIdBytes();
  }
  /**
   * Protobuf type {@code RemoveExpansions}
   */
  public static final class RemoveExpansions extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RemoveExpansions)
      RemoveExpansionsOrBuilder {
    // Use RemoveExpansions.newBuilder() to construct.
    private RemoveExpansions(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RemoveExpansions(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RemoveExpansions defaultInstance;
    public static RemoveExpansions getDefaultInstance() {
      return defaultInstance;
    }

    public RemoveExpansions getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RemoveExpansions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              senseId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hello.suripu.api.cleanup.CleanUp.internal_static_RemoveExpansions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hello.suripu.api.cleanup.CleanUp.internal_static_RemoveExpansions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.class, com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.Builder.class);
    }

    public static com.google.protobuf.Parser<RemoveExpansions> PARSER =
        new com.google.protobuf.AbstractParser<RemoveExpansions>() {
      public RemoveExpansions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RemoveExpansions(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RemoveExpansions> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SENSE_ID_FIELD_NUMBER = 1;
    private java.lang.Object senseId_;
    /**
     * <code>required string sense_id = 1;</code>
     */
    public boolean hasSenseId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sense_id = 1;</code>
     */
    public java.lang.String getSenseId() {
      java.lang.Object ref = senseId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senseId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sense_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSenseIdBytes() {
      java.lang.Object ref = senseId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senseId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      senseId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSenseId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSenseIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSenseIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RemoveExpansions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RemoveExpansions)
        com.hello.suripu.api.cleanup.CleanUp.RemoveExpansionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hello.suripu.api.cleanup.CleanUp.internal_static_RemoveExpansions_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hello.suripu.api.cleanup.CleanUp.internal_static_RemoveExpansions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.class, com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.Builder.class);
      }

      // Construct using com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        senseId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hello.suripu.api.cleanup.CleanUp.internal_static_RemoveExpansions_descriptor;
      }

      public com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions getDefaultInstanceForType() {
        return com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.getDefaultInstance();
      }

      public com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions build() {
        com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions buildPartial() {
        com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions result = new com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.senseId_ = senseId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions) {
          return mergeFrom((com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions other) {
        if (other == com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions.getDefaultInstance()) return this;
        if (other.hasSenseId()) {
          bitField0_ |= 0x00000001;
          senseId_ = other.senseId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSenseId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hello.suripu.api.cleanup.CleanUp.RemoveExpansions) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object senseId_ = "";
      /**
       * <code>required string sense_id = 1;</code>
       */
      public boolean hasSenseId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sense_id = 1;</code>
       */
      public java.lang.String getSenseId() {
        java.lang.Object ref = senseId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senseId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sense_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSenseIdBytes() {
        java.lang.Object ref = senseId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senseId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sense_id = 1;</code>
       */
      public Builder setSenseId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        senseId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sense_id = 1;</code>
       */
      public Builder clearSenseId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        senseId_ = getDefaultInstance().getSenseId();
        onChanged();
        return this;
      }
      /**
       * <code>required string sense_id = 1;</code>
       */
      public Builder setSenseIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        senseId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RemoveExpansions)
    }

    static {
      defaultInstance = new RemoveExpansions(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RemoveExpansions)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CleanupMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CleanupMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DisableAccount_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DisableAccount_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExpireOAuthTokens_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ExpireOAuthTokens_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoveExpansions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RemoveExpansions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcleanup.proto\"\277\001\n\016CleanupMessage\022\021\n\tre" +
      "quester\030\001 \002(\t\022\021\n\ttimestamp\030\002 \001(\003\022(\n\017disa" +
      "ble_account\030\003 \001(\0132\017.DisableAccount\022/\n\023ex" +
      "pire_oauth_tokens\030\004 \001(\0132\022.ExpireOAuthTok" +
      "ens\022,\n\021remove_expansions\030\005 \001(\0132\021.RemoveE" +
      "xpansions\"3\n\016DisableAccount\022\022\n\naccount_i" +
      "d\030\001 \002(\003\022\r\n\005email\030\002 \002(\t\"\'\n\021ExpireOAuthTok" +
      "ens\022\022\n\naccount_id\030\001 \002(\003\"$\n\020RemoveExpansi" +
      "ons\022\020\n\010sense_id\030\001 \002(\tB\'\n\034com.hello.surip" +
      "u.api.cleanupB\007CleanUp"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CleanupMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CleanupMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CleanupMessage_descriptor,
        new java.lang.String[] { "Requester", "Timestamp", "DisableAccount", "ExpireOauthTokens", "RemoveExpansions", });
    internal_static_DisableAccount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DisableAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DisableAccount_descriptor,
        new java.lang.String[] { "AccountId", "Email", });
    internal_static_ExpireOAuthTokens_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ExpireOAuthTokens_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ExpireOAuthTokens_descriptor,
        new java.lang.String[] { "AccountId", });
    internal_static_RemoveExpansions_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RemoveExpansions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RemoveExpansions_descriptor,
        new java.lang.String[] { "SenseId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
