metrics_enabled: true
debug: false
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - com.hello

common_db:
  driverClass: org.postgresql.Driver
  user: common
  password: hello-common
  url: jdbc:postgresql://common.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/common
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 4

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  checkConnectionHealthWhenIdleFor: 10s

  # the maximum lifetime of an idle connection
  closeConnectionIfIdleFor: 1 minute

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    batch_pill_data : batch_pill_data

app_name: PillScoreConsumerProd

max_records: 1000

# minutes of data to store in memory before processing
date_minutes_bucket: 15

# no. of pills/records to process before kinesis checkpoint
# we want this number to be roughly no. of pills in the wild
checkpoint_threshold: 200

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.hello.suripu.workers: DEBUG

pill_key_store:
  endpoint : http://dynamodb.us-east-1.amazonaws.com
  region: us-east-1
  table_name: pill_key_store

user_info:
  endpoint : http://dynamodb.us-east-1.amazonaws.com
  region: us-east-1
  table_name: prod_alarm_info

features_db:
    endpoint : http://dynamodb.us-east-1.amazonaws.com
    region: us-east-1
    table_name: features

redis:
  host: stats.xoe7je.0001.use1.cache.amazonaws.com
  port: 6379


kinesis_logger:
  stream_name: logs
  enabled : true
  buffer_size: 100
  origin: suripu-workers
  min_log_level : INFO