// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: provision.proto

package com.hello.suripu.api.provision;

public final class ProvisionProtos {
  private ProvisionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProvisionRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string device_id = 1;
    /**
     * <code>required string device_id = 1;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>required string device_id = 1;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>required string device_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    // required bool need_key = 2;
    /**
     * <code>required bool need_key = 2;</code>
     */
    boolean hasNeedKey();
    /**
     * <code>required bool need_key = 2;</code>
     */
    boolean getNeedKey();

    // required string serial = 3;
    /**
     * <code>required string serial = 3;</code>
     */
    boolean hasSerial();
    /**
     * <code>required string serial = 3;</code>
     */
    java.lang.String getSerial();
    /**
     * <code>required string serial = 3;</code>
     */
    com.google.protobuf.ByteString
        getSerialBytes();
  }
  /**
   * Protobuf type {@code ProvisionRequest}
   */
  public static final class ProvisionRequest extends
      com.google.protobuf.GeneratedMessage
      implements ProvisionRequestOrBuilder {
    // Use ProvisionRequest.newBuilder() to construct.
    private ProvisionRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProvisionRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProvisionRequest defaultInstance;
    public static ProvisionRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ProvisionRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProvisionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              needKey_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              serial_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hello.suripu.api.provision.ProvisionProtos.internal_static_ProvisionRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hello.suripu.api.provision.ProvisionProtos.internal_static_ProvisionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest.class, com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ProvisionRequest> PARSER =
        new com.google.protobuf.AbstractParser<ProvisionRequest>() {
      public ProvisionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProvisionRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProvisionRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string device_id = 1;
    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private java.lang.Object deviceId_;
    /**
     * <code>required string device_id = 1;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string device_id = 1;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string device_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bool need_key = 2;
    public static final int NEED_KEY_FIELD_NUMBER = 2;
    private boolean needKey_;
    /**
     * <code>required bool need_key = 2;</code>
     */
    public boolean hasNeedKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool need_key = 2;</code>
     */
    public boolean getNeedKey() {
      return needKey_;
    }

    // required string serial = 3;
    public static final int SERIAL_FIELD_NUMBER = 3;
    private java.lang.Object serial_;
    /**
     * <code>required string serial = 3;</code>
     */
    public boolean hasSerial() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string serial = 3;</code>
     */
    public java.lang.String getSerial() {
      java.lang.Object ref = serial_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serial_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serial = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSerialBytes() {
      java.lang.Object ref = serial_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      deviceId_ = "";
      needKey_ = false;
      serial_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNeedKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSerial()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, needKey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSerialBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, needKey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSerialBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProvisionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hello.suripu.api.provision.ProvisionProtos.internal_static_ProvisionRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hello.suripu.api.provision.ProvisionProtos.internal_static_ProvisionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest.class, com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest.Builder.class);
      }

      // Construct using com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        needKey_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        serial_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hello.suripu.api.provision.ProvisionProtos.internal_static_ProvisionRequest_descriptor;
      }

      public com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest getDefaultInstanceForType() {
        return com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest.getDefaultInstance();
      }

      public com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest build() {
        com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest buildPartial() {
        com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest result = new com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.needKey_ = needKey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serial_ = serial_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest) {
          return mergeFrom((com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest other) {
        if (other == com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000001;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasNeedKey()) {
          setNeedKey(other.getNeedKey());
        }
        if (other.hasSerial()) {
          bitField0_ |= 0x00000004;
          serial_ = other.serial_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeviceId()) {
          
          return false;
        }
        if (!hasNeedKey()) {
          
          return false;
        }
        if (!hasSerial()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hello.suripu.api.provision.ProvisionProtos.ProvisionRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string device_id = 1;
      private java.lang.Object deviceId_ = "";
      /**
       * <code>required string device_id = 1;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }

      // required bool need_key = 2;
      private boolean needKey_ ;
      /**
       * <code>required bool need_key = 2;</code>
       */
      public boolean hasNeedKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool need_key = 2;</code>
       */
      public boolean getNeedKey() {
        return needKey_;
      }
      /**
       * <code>required bool need_key = 2;</code>
       */
      public Builder setNeedKey(boolean value) {
        bitField0_ |= 0x00000002;
        needKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool need_key = 2;</code>
       */
      public Builder clearNeedKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        needKey_ = false;
        onChanged();
        return this;
      }

      // required string serial = 3;
      private java.lang.Object serial_ = "";
      /**
       * <code>required string serial = 3;</code>
       */
      public boolean hasSerial() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string serial = 3;</code>
       */
      public java.lang.String getSerial() {
        java.lang.Object ref = serial_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serial_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serial = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSerialBytes() {
        java.lang.Object ref = serial_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serial_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serial = 3;</code>
       */
      public Builder setSerial(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serial_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serial = 3;</code>
       */
      public Builder clearSerial() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serial_ = getDefaultInstance().getSerial();
        onChanged();
        return this;
      }
      /**
       * <code>required string serial = 3;</code>
       */
      public Builder setSerialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serial_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProvisionRequest)
    }

    static {
      defaultInstance = new ProvisionRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProvisionRequest)
  }

  public interface ProvisionResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes key = 1;
    /**
     * <code>optional bytes key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>optional bytes key = 1;</code>
     */
    com.google.protobuf.ByteString getKey();

    // optional bool retry = 2;
    /**
     * <code>optional bool retry = 2;</code>
     */
    boolean hasRetry();
    /**
     * <code>optional bool retry = 2;</code>
     */
    boolean getRetry();
  }
  /**
   * Protobuf type {@code ProvisionResponse}
   */
  public static final class ProvisionResponse extends
      com.google.protobuf.GeneratedMessage
      implements ProvisionResponseOrBuilder {
    // Use ProvisionResponse.newBuilder() to construct.
    private ProvisionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProvisionResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProvisionResponse defaultInstance;
    public static ProvisionResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ProvisionResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProvisionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              retry_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hello.suripu.api.provision.ProvisionProtos.internal_static_ProvisionResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hello.suripu.api.provision.ProvisionProtos.internal_static_ProvisionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse.class, com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ProvisionResponse> PARSER =
        new com.google.protobuf.AbstractParser<ProvisionResponse>() {
      public ProvisionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProvisionResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProvisionResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString key_;
    /**
     * <code>optional bytes key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes key = 1;</code>
     */
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }

    // optional bool retry = 2;
    public static final int RETRY_FIELD_NUMBER = 2;
    private boolean retry_;
    /**
     * <code>optional bool retry = 2;</code>
     */
    public boolean hasRetry() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool retry = 2;</code>
     */
    public boolean getRetry() {
      return retry_;
    }

    private void initFields() {
      key_ = com.google.protobuf.ByteString.EMPTY;
      retry_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, retry_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, retry_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProvisionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hello.suripu.api.provision.ProvisionProtos.internal_static_ProvisionResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hello.suripu.api.provision.ProvisionProtos.internal_static_ProvisionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse.class, com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse.Builder.class);
      }

      // Construct using com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        retry_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hello.suripu.api.provision.ProvisionProtos.internal_static_ProvisionResponse_descriptor;
      }

      public com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse getDefaultInstanceForType() {
        return com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse.getDefaultInstance();
      }

      public com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse build() {
        com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse buildPartial() {
        com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse result = new com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.retry_ = retry_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse) {
          return mergeFrom((com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse other) {
        if (other == com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasRetry()) {
          setRetry(other.getRetry());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hello.suripu.api.provision.ProvisionProtos.ProvisionResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes key = 1;
      private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes key = 1;</code>
       */
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }
      /**
       * <code>optional bytes key = 1;</code>
       */
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }

      // optional bool retry = 2;
      private boolean retry_ ;
      /**
       * <code>optional bool retry = 2;</code>
       */
      public boolean hasRetry() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool retry = 2;</code>
       */
      public boolean getRetry() {
        return retry_;
      }
      /**
       * <code>optional bool retry = 2;</code>
       */
      public Builder setRetry(boolean value) {
        bitField0_ |= 0x00000002;
        retry_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool retry = 2;</code>
       */
      public Builder clearRetry() {
        bitField0_ = (bitField0_ & ~0x00000002);
        retry_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProvisionResponse)
    }

    static {
      defaultInstance = new ProvisionResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProvisionResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProvisionRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProvisionRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProvisionResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProvisionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017provision.proto\"G\n\020ProvisionRequest\022\021\n" +
      "\tdevice_id\030\001 \002(\t\022\020\n\010need_key\030\002 \002(\010\022\016\n\006se" +
      "rial\030\003 \002(\t\"/\n\021ProvisionResponse\022\013\n\003key\030\001" +
      " \001(\014\022\r\n\005retry\030\002 \001(\010B1\n\036com.hello.suripu." +
      "api.provisionB\017ProvisionProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ProvisionRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ProvisionRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProvisionRequest_descriptor,
              new java.lang.String[] { "DeviceId", "NeedKey", "Serial", });
          internal_static_ProvisionResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ProvisionResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProvisionResponse_descriptor,
              new java.lang.String[] { "Key", "Retry", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
