# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matrix.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='matrix.proto',
  package='hello',
  serialized_pb='\n\x0cmatrix.proto\x12\x05hello\"\\\n\x13MatrixClientMessage\x12\x0b\n\x03mac\x18\x01 \x01(\x0c\x12\x11\n\tunix_time\x18\x02 \x01(\x05\x12%\n\x0ematrix_payload\x18\x03 \x01(\x0b\x32\r.hello.Matrix\"\xd4\x01\n\x06Matrix\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04rows\x18\x02 \x02(\x05\x12\x0c\n\x04\x63ols\x18\x03 \x02(\x05\x12(\n\x08\x64\x61tatype\x18\x04 \x02(\x0e\x32\x16.hello.Matrix.DataType\x12\r\n\x05idata\x18\x05 \x03(\x11\x12\r\n\x05\x66\x64\x61ta\x18\x06 \x03(\x02\x12\r\n\x05time1\x18\x07 \x02(\x03\x12\r\n\x05time2\x18\x08 \x02(\x03\x12\x0c\n\x04tags\x18\t \x02(\t\x12\x0e\n\x06source\x18\n \x02(\t\"\x1e\n\x08\x44\x61taType\x12\t\n\x05\x46LOAT\x10\x00\x12\x07\n\x03INT\x10\x01\x42*\n\x1a\x63om.hello.suripu.api.audioB\x0cMatrixProtos')



_MATRIX_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='hello.Matrix.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=300,
  serialized_end=330,
)


_MATRIXCLIENTMESSAGE = _descriptor.Descriptor(
  name='MatrixClientMessage',
  full_name='hello.MatrixClientMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mac', full_name='hello.MatrixClientMessage.mac', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unix_time', full_name='hello.MatrixClientMessage.unix_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='matrix_payload', full_name='hello.MatrixClientMessage.matrix_payload', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=115,
)


_MATRIX = _descriptor.Descriptor(
  name='Matrix',
  full_name='hello.Matrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hello.Matrix.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='hello.Matrix.rows', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cols', full_name='hello.Matrix.cols', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datatype', full_name='hello.Matrix.datatype', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='idata', full_name='hello.Matrix.idata', index=4,
      number=5, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fdata', full_name='hello.Matrix.fdata', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time1', full_name='hello.Matrix.time1', index=6,
      number=7, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time2', full_name='hello.Matrix.time2', index=7,
      number=8, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='hello.Matrix.tags', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='hello.Matrix.source', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MATRIX_DATATYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=118,
  serialized_end=330,
)

_MATRIXCLIENTMESSAGE.fields_by_name['matrix_payload'].message_type = _MATRIX
_MATRIX.fields_by_name['datatype'].enum_type = _MATRIX_DATATYPE
_MATRIX_DATATYPE.containing_type = _MATRIX;
DESCRIPTOR.message_types_by_name['MatrixClientMessage'] = _MATRIXCLIENTMESSAGE
DESCRIPTOR.message_types_by_name['Matrix'] = _MATRIX

class MatrixClientMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MATRIXCLIENTMESSAGE

  # @@protoc_insertion_point(class_scope:hello.MatrixClientMessage)

class Matrix(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MATRIX

  # @@protoc_insertion_point(class_scope:hello.Matrix)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\032com.hello.suripu.api.audioB\014MatrixProtos')
# @@protoc_insertion_point(module_scope)
